import type { Copy } from "./copy.types";
import { draft } from "./draft";

export const nl: Copy = {
  siteName: "Supreme Real Estate",
  meta: {
    homeTitle: "Supreme Real Estate · Van oud naar waardevol",
    titlePattern: (page) => `${page} · Supreme Real Estate`,
    description: "Supreme Real Estate is een vastgoedonderneming in Amsterdam, gericht op bestaande woningen en de lange termijn.",
    pages: {
      about: { title: "Over ons", description: draft("Over Supreme Real Estate: waar wij voor staan en onze bedrijfsgegevens.") },
      contact: { title: "Contact", description: draft("Neem contact op met Supreme Real Estate voor samenwerking, pers of andere vragen.") },
      privacy: { title: "Privacybeleid", description: draft("Privacybeleid van Supreme Real Estate.") },
      cookies: { title: "Cookiebeleid", description: draft("Cookiebeleid van Supreme Real Estate.") },
      disclaimer: { title: "Disclaimer", description: draft("Disclaimer van Supreme Real Estate.") },
      colophon: { title: "Colofon", description: draft("Colofon van Supreme Real Estate: bedrijfsgegevens en credits.") },
    },
    notFoundTitle: "Deze pagina bestaat niet (meer)",
  },
  a11y: {
    skip: draft("Naar inhoud"),
    languageSwitch: draft("Taal"),
    nl: "Nederlands",
    en: "English",
    mainNav: draft("Hoofdmenu"),
    footerNav: draft("Juridisch"),
    legalNav: draft("Juridische pagina's"),
    home: draft("Supreme Real Estate, naar de homepage"),
  },
  nav: { about: "Over ons", contact: "Contact", menu: "Menu", closeMenu: "Sluit menu" },
  brand: { wordmark: "SUPREME", descriptor: "REAL ESTATE", tagline: "Van oud naar waardevol" },
  hero: {
    // PRD §6.1: what the public site may say, in one sentence (APPROVED lead sentence used as H1).
    display: "Supreme Real Estate is een vastgoedonderneming in Amsterdam, gericht op bestaande woningen en de lange termijn.",
    // Body built from the three principles (DESIGN §10.1 §3) and the brand promise; no figures, no superlatives.
    lead: draft("Wij kiezen bestaande woningen met aandacht en vernieuwen ze met vakmanschap, om generaties mee te gaan. Wij denken in decennia, niet in transacties. Van oud naar waardevol."),
    primary: "Neem contact op",
    secondary: "Over Supreme",
    coordinates: "52.37° N · 4.90° E — Amsterdam",
    pause: "Pauzeer video",
    play: "Speel video af",
    filmCaption: "Amsterdam",
  },
  statement: {
    label: "01 — Supreme",
    text: "Wij zien wat een woning kan worden, en geven haar met zorg een nieuwe toekomst. Zorgvuldig gekozen, met vakmanschap vernieuwd, voor de lange termijn.",
    aside: draft("Geen snelle transacties. Wij werken met een horizon van decennia, in de stad waar we thuis zijn."),
  },
  principles: {
    label: "02 — Principes",
    title: "Waar wij voor staan",
    sub: draft("Drie principes achter elke keuze."),
    items: [
      { index: "01", title: "Zorgvuldig", body: "Wij kiezen met aandacht en werken met mensen die vakmanschap leveren." },
      { index: "02", title: "Blijvend", body: "Wat wij vernieuwen, moet generaties meegaan." },
      { index: "03", title: "Lange termijn", body: "Wij denken in decennia, niet in transacties." },
    ],
  },
  carousel: {
    label: "03 — Details",
    title: "Materiaal, licht en ruimte",
    sub: draft("Wat blijft, begint bij wat je aanraakt en ziet."),
    items: [
      { title: draft("Materiaal"), body: draft("Kalk, steen, eik en messing. Materialen die mooier worden met de tijd.") },
      { title: draft("Licht"), body: draft("Daglicht als bouwmateriaal: hoog, zacht en de hele dag aanwezig.") },
      { title: draft("Ruimte"), body: draft("Ruimte die rust geeft, met maat en proportie die kloppen.") },
    ],
  },
  map: {
    label: draft("04 — Amsterdam"),
    title: draft("Thuis in Amsterdam"),
    sub: draft("Wij werken in de stad waar we thuis zijn, met respect voor wat er al staat."),
    cta: "Over Supreme",
    dot: "Amsterdam",
  },
  closing: {
    title: draft("Gemaakt om te blijven"),
    body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    cta: "Neem contact op",
    marquee: "Van oud naar waardevol",
  },
  details: {
    label: "03 — Details",
    title: "Materiaal, licht en ruimte",
    counter: (i, n) => `${i} / ${n}`,
    scrollerLabel: draft("Beelden van materiaal, licht en ruimte"),
  },
  companySection: { label: draft("05 — Bedrijf"), title: "Bedrijfsgegevens" },
  companyKeys: {
    legalName: "Statutaire naam",
    tradeName: "Handelsnaam",
    kvk: "KvK-nummer",
    visitingAddress: "Vestigingsadres",
    postalAddress: "Postadres",
    vat: "BTW-nummer",
    email: "E-mail",
    emailLegal: draft("E-mail (juridisch)"),
    phone: "Telefoon",
    availability: "Bereikbaar",
    management: "Bestuur",
    linkedin: "LinkedIn",
  },
  companyLegalLine: "Voor juridische of compliance-vragen",
  contactSection: {
    label: draft("06 — Contact"),
    title: "Neem contact op",
    body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    cta: "Neem contact op",
  },
  contactPage: {
    title: "Contact",
    lead: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    methodsTitle: draft("Bereik ons"),
    formTitle: draft("Stuur een bericht"),
  },
  form: {
    name: "Naam",
    organisation: "Organisatie",
    email: "E-mail",
    phone: "Telefoon",
    subject: "Onderwerp",
    message: "Bericht",
    optional: "optioneel",
    subjects: [
      { value: "samenwerking", label: "Samenwerking" },
      { value: "pers", label: "Pers" },
      { value: "juridisch", label: "Juridisch / compliance" },
      { value: "overig", label: "Overig" },
    ],
    subjectPlaceholder: draft("Kies een onderwerp"),
    consent: draft("Ik ga akkoord met de verwerking van mijn gegevens volgens het"),
    consentLink: "Privacybeleid",
    submit: "Stuur bericht",
    sending: draft("Versturen…"),
    success: "Bedankt. We nemen persoonlijk contact met je op.",
    errors: {
      required: "Dit veld is verplicht.",
      email: "Vul een geldig e-mailadres in.",
      consent: draft("Ga akkoord met het privacybeleid om het bericht te versturen."),
      tooLong: draft("Dit veld is te lang."),
      rateLimited: draft("Te veel berichten in korte tijd. Probeer het later opnieuw."),
      failed: draft("Het bericht kon niet worden verstuurd. Probeer het later opnieuw of stuur een e-mail."),
    },
  },
  about: {
    title: "Over ons",
    promiseLabel: draft("Belofte"),
    promise: "Van oud naar waardevol",
    managementTitle: "Bestuur",
  },
  legal: {
    lastUpdated: "Laatst bijgewerkt",
    placeholderNote: "Placeholder: definitieve tekst volgt van legal.",
  },
  footer: {
    links: [
      { key: "privacy", label: "Privacybeleid" },
      { key: "cookies", label: "Cookiebeleid" },
      { key: "disclaimer", label: "Disclaimer" },
      { key: "colophon", label: "Colofon" },
    ],
    copyright: (year) => `© ${year}`,
    kvk: "KvK",
    vat: "BTW",
    linkedin: "LinkedIn",
  },
  notFound: { title: "Deze pagina bestaat niet (meer)", home: draft("Terug naar de homepage") },
  placeholders: {
    description: "Placeholder: geverifieerde bedrijfsomschrijving (2–3 zinnen) volgt van Supreme.",
    story: "Placeholder: kort, geverifieerd bedrijfsverhaal volgt van Supreme.",
    media: "Placeholder: gelicentieerde fotografie volgt.",
    film: "Placeholder: herofilm en poster volgen van de filmmaker.",
    credits: "Placeholder: foto- en filmcredits volgen van Supreme.",
  },
};
