import type { Copy } from "./copy.types";
import { draft } from "./draft";

export const nl: Copy = {
  siteName: "Supreme Real Estate",
  meta: {
    homeTitle: "Supreme Real Estate · Van oud naar waardevol",
    titlePattern: (page) => `${page} · Supreme Real Estate`,
    description: "Supreme Real Estate is een vastgoedonderneming in Amsterdam, gericht op bestaande woningen en de lange termijn.",
    pages: {
      about: { title: "Over ons", description: draft("Over Supreme Real Estate: waar wij voor staan en onze bedrijfsgegevens.") },
      contact: { title: "Contact", description: draft("Neem contact op met Supreme Real Estate voor samenwerking, pers of andere vragen.") },
      privacy: { title: "Privacybeleid", description: draft("Privacybeleid van Supreme Real Estate.") },
      cookies: { title: "Cookiebeleid", description: draft("Cookiebeleid van Supreme Real Estate.") },
      disclaimer: { title: "Disclaimer", description: draft("Disclaimer van Supreme Real Estate.") },
      colophon: { title: "Colofon", description: draft("Colofon van Supreme Real Estate: bedrijfsgegevens en credits.") },
    },
    notFoundTitle: "Deze pagina bestaat niet (meer)",
  },
  a11y: {
    skip: draft("Naar inhoud"),
    languageSwitch: draft("Taal"),
    nl: "Nederlands",
    en: "English",
    mainNav: draft("Hoofdmenu"),
    footerNav: draft("Juridisch"),
    legalNav: draft("Juridische pagina's"),
    home: draft("Supreme Real Estate, naar de homepage"),
  },
  nav: {
    about: "Over ons",
    contact: "Contact",
    menu: draft("Navigeer naar"),
    closeMenu: "Sluit menu",
    contactUs: "Neem contact op",
    sections: [
      { id: "home", label: draft("Home") },
      { id: "about", label: "Over ons" },
      { id: "approach", label: draft("Werkwijze") },
      { id: "work", label: draft("Werk") },
    ],
  },
  brand: { wordmark: "SUPREME", descriptor: "REAL ESTATE", tagline: "Van oud naar waardevol" },
  hero: {
    // Hero concept 2026-09-30 (owner-supplied English copy, NL draft). The approved brand promise
    // "Van oud naar waardevol." stays in the docs; restore it here if the concept copy is not approved.
    headline: draft("Meer dan ruimte\nom te wonen"),
    keyMessage: draft("Waarde creëren door vastgoed en visie."),
    pause: "Pauzeer video",
    play: "Speel video af",
  },
  // Shelf statement: owner concept 2026-09-30, NL draft until approved.
  shelf: {
    parts: [draft("Wij zien de mogelijkheden van bestaande"), { icon: "bulb" }, draft("panden, vernieuwen"), { icon: "hammer" }, draft("ze tot zorgvuldig ontworpen woningen en blijven"), { icon: "clipboard" }, draft("hun waarde beheren, jaar na jaar"), { icon: "chart" }],
  },
  // Steps: owner concept 2026-10-01, NL draft until approved.
  steps: {
    label: draft("Waarde opnieuw bekeken"),
    lines: [draft("Potentieel ontsluiten."), draft("Panden transformeren."), draft("Blijvende waarde creëren.")],
    items: [
      { index: "01", title: draft("Herzien"), body: draft("Begrijpen wat een bestaand pand is en kan worden.") },
      { index: "02", title: draft("Verdelen"), body: draft("Grotere ruimtes omvormen tot zelfstandige woningen.") },
      { index: "03", title: draft("Opleveren"), body: draft("Elke woning turnkey opleveren als een plek om te wonen.") },
    ],
  },
  // Work section (2026-10-02): vier cases uit het archief van de eigenaar, anoniem zolang PRD §6 dat vraagt.
  work: {
    label: draft("Geselecteerd werk"),
    title: draft("Vier woningen, van oud naar waardevol."),
    lead: draft("Een selectie van afgeronde renovaties. Alleen interieurs: adressen publiceren we niet."),
    of: draft("van"),
    open: draft("Bekijk project"),
    back: draft("Werk"),
    next: draft("Volgend project"),
    more: draft("Meer werk."),
    continueLabel: draft("Verder"),
    close: draft("Sluiten"),
    facts: { home: draft("Woning"), scope: draft("Werk"), delivery: draft("Oplevering"), status: draft("Status") },
    slider: { label: draft("Foto's"), previous: draft("Vorige foto"), nextSlide: draft("Volgende foto") },
    compare: { before: draft("Voor"), after: draft("Na"), label: draft("Vergelijk voor en na") },
    items: [
      {
        index: "01", title: draft("Licht van twee kanten"), body: draft("Een bestaande woning, opnieuw ingedeeld rond een lichte woonkeuken."),
        facts: { home: draft("Appartement"), scope: draft("Indeling · keuken · badkamer"), delivery: draft("Turnkey"), status: draft("Opgeleverd") },
        notes: [
          { title: draft("Herzien"), body: draft("Een gesloten plattegrond met kleine kamers, en daglicht van twee kanten dat de oude indeling nooit gebruikte.") },
          { title: draft("Verdelen"), body: draft("Eén open woonkeuken, met de slaapkamers en de badkamer apart gehouden.") },
          { title: draft("Opleveren"), body: draft("Tot in detail afgewerkt: keuken, badkamer en vloeren, klaar om in te wonen.") },
        ],
        chapters: [
          { key: draft("Licht"), statement: draft("Muren gingen weg waar het licht binnenkwam. De keuken staat nu midden in de dag, niet aan het eind van een gang.") },
          { key: draft("Materiaal"), statement: draft("Licht eiken, een stenen werkblad en messing kranen: weinig materialen, gekozen om mooi oud te worden en elke dag aangeraakt te worden.") },
          { key: draft("Thuis"), statement: draft("Geen showroom. Een rustig, afgewerkt huis waar de eerste avond al voelt als wonen.") },
        ],
      },
      {
        index: "02", title: draft("Donker hout, warm licht"), body: draft("Een compacte plattegrond met een hoge keukenwand en een rustige badkamer."),
        facts: { home: draft("Appartement"), scope: draft("Keukenwand · badkamer · afwerking"), delivery: draft("Turnkey, ingericht"), status: draft("Opgeleverd") },
        notes: [
          { title: draft("Herzien"), body: draft("Een compacte plattegrond waar elke vierkante meter moet werken.") },
          { title: draft("Verdelen"), body: draft("Eén hoge keukenwand draagt koken, bergen en zitten; de badkamer blijft rustig en apart.") },
          { title: draft("Opleveren"), body: draft("Donker hout, steen en messing, opgeleverd als één rustig geheel.") },
        ],
        chapters: [
          { key: draft("Hout"), statement: draft("Eén donkere wand draagt de hele keuken, zodat de rest van de ruimte leeg en licht kan blijven.") },
          { key: draft("Steen"), statement: draft("Warme steen op de vloer en het werkblad, een ronde spiegel en messing in de badkamer: kleine ruimtes, volle aandacht.") },
          { key: draft("Thuis"), statement: draft("Compact, maar nooit krap. Alles heeft zijn plek, en die plek heeft een stemming.") },
        ],
      },
      {
        index: "03", title: draft("Steen en messing"), body: draft("Natuursteen, messing kranen en een slaapkamer onder het dak."),
        facts: { home: draft("Bovenwoning met zolder"), scope: draft("Zolder · keuken · badkamer"), delivery: draft("Turnkey"), status: draft("Opgeleverd") },
        notes: [
          { title: draft("Herzien"), body: draft("Een dak dat meer kon dragen dan berging.") },
          { title: draft("Verdelen"), body: draft("De zolder opengemaakt voor een slaapkamer; keuken en badkamer beneden vernieuwd rond een stenen werkblad.") },
          { title: draft("Opleveren"), body: draft("Natuursteen, messing en zachte kleur, turnkey afgewerkt.") },
        ],
        chapters: [
          { key: draft("Dak"), statement: draft("De zolder is opengemaakt vanaf de spanten. Wat berging was, is nu de rustigste kamer van het huis.") },
          { key: draft("Steen"), statement: draft("Een geaderd stenen werkblad, steen in de douche, messing op de kranen: het materiaal doet het decoreren.") },
          { key: draft("Thuis"), statement: draft("Zachte kleur onder een hoog dak. Een huis dat gemaakt voelt, niet geplaatst.") },
        ],
      },
      {
        index: "04", title: draft("Ruimte om te ademen"), body: draft("Royale kamers, een rustige badkamer en een slaapkamer met uitzicht."),
        facts: { home: draft("Appartement"), scope: draft("Indeling · badkamer · afwerking"), delivery: draft("Turnkey"), status: draft("Opgeleverd") },
        notes: [
          { title: draft("Herzien"), body: draft("Royale kamers die alleen een duidelijker orde nodig hadden.") },
          { title: draft("Verdelen"), body: draft("Wonen en eten in één open ruimte, badkamer en slaapkamers naar achteren.") },
          { title: draft("Opleveren"), body: draft("Lichte afwerking, een rustige badkamer en een slaapkamer die haar uitzicht houdt.") },
        ],
        chapters: [
          { key: draft("Ruimte"), statement: draft("De kamers waren al royaal. Het werk was ze orde te geven, en ze daarna met rust te laten.") },
          { key: draft("Rust"), statement: draft("Een badkamer in één lichte toon, een eethoek bij het raam: niets schreeuwt, alles is af.") },
          { key: draft("Thuis"), statement: draft("Een plek om te ademen. Compleet opgeleverd, met het uitzicht precies waar het was.") },
        ],
      },
    ],
  },
  // Sky band: owner concept 2026-10-01, NL draft until approved.
  sky: {
    label: draft("Van"),
    title: draft("Potentieel naar turnkey"),
    lead: draft("Wij transformeren bestaande panden tot zorgvuldig ontworpen, instapklare woningen."),
    ctaPrimary: draft("Onze werkwijze"),
    ctaSecondary: draft("Bekijk projecten"),
    cards: [
      { title: draft("Pand"), body: draft("Bestaand") },
      { title: draft("Verwerven"), body: draft("Bestaande panden met potentieel") },
      { title: draft("Herzien"), body: draft("Een nieuwe visie op waardevolle ruimte") },
      { title: draft("Getransformeerd"), body: draft("Zorgvuldige ontwikkeling en hoogwaardig ontwerp") },
      { title: draft("Verfijnd"), body: draft("Modern wonen met tijdloze details") },
      { title: draft("Turnkey"), body: draft("Instapklare woningen, afgewerkt op hoog niveau") },
      { title: draft("Pand"), body: draft("Opgeleverd") },
    ],
  },
  statement: {
    label: "01 — Supreme",
    text: "Wij zien wat een woning kan worden, en geven haar met zorg een nieuwe toekomst. Zorgvuldig gekozen, met vakmanschap vernieuwd, voor de lange termijn.",
    aside: draft("Geen snelle transacties. Wij werken met een horizon van decennia, in de stad waar we thuis zijn."),
  },
  principles: {
    label: "02 — Principes",
    title: "Waar wij voor staan",
    sub: draft("Drie principes achter elke keuze."),
    items: [
      { index: "01", title: "Zorgvuldig", body: "Wij kiezen met aandacht en werken met mensen die vakmanschap leveren." },
      { index: "02", title: "Blijvend", body: "Wat wij vernieuwen, moet generaties meegaan." },
      { index: "03", title: "Lange termijn", body: "Wij denken in decennia, niet in transacties." },
    ],
  },
  carousel: {
    label: "03 — Details",
    title: "Materiaal, licht en ruimte",
    sub: draft("Wat blijft, begint bij wat je aanraakt en ziet."),
    items: [
      { title: draft("Materiaal"), body: draft("Kalk, steen, eik en messing. Materialen die mooier worden met de tijd.") },
      { title: draft("Licht"), body: draft("Daglicht als bouwmateriaal: hoog, zacht en de hele dag aanwezig.") },
      { title: draft("Ruimte"), body: draft("Ruimte die rust geeft, met maat en proportie die kloppen.") },
    ],
  },
  map: {
    label: draft("04 — Amsterdam"),
    title: draft("Thuis in Amsterdam"),
    sub: draft("Wij werken in de stad waar we thuis zijn, met respect voor wat er al staat."),
    cta: "Over Supreme",
    dot: "Amsterdam",
  },
  closing: {
    title: draft("Gemaakt om te blijven"),
    body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    cta: "Neem contact op",
    marquee: "Van oud naar waardevol",
  },
  details: {
    label: "03 — Details",
    title: "Materiaal, licht en ruimte",
    counter: (i, n) => `${i} / ${n}`,
    scrollerLabel: draft("Beelden van materiaal, licht en ruimte"),
  },
  companySection: { label: draft("04 — Bedrijf"), title: "Bedrijfsgegevens" },
  companyKeys: {
    legalName: "Statutaire naam",
    tradeName: "Handelsnaam",
    kvk: "KvK-nummer",
    visitingAddress: "Vestigingsadres",
    postalAddress: "Postadres",
    vat: "BTW-nummer",
    email: "E-mail",
    emailLegal: draft("E-mail (juridisch)"),
    phone: "Telefoon",
    availability: "Bereikbaar",
    management: "Bestuur",
    linkedin: "LinkedIn",
  },
  companyLegalLine: "Voor juridische of compliance-vragen",
  contactSection: {
    label: draft("05 — Contact"),
    title: "Neem contact op",
    body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    cta: "Neem contact op",
  },
  contactPage: {
    title: "Contact",
    lead: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    methodsTitle: draft("Bereik ons"),
    formTitle: draft("Stuur een bericht"),
  },
  form: {
    name: "Naam",
    organisation: "Organisatie",
    email: "E-mail",
    phone: "Telefoon",
    subject: "Onderwerp",
    message: "Bericht",
    optional: "optioneel",
    subjects: [
      { value: "samenwerking", label: "Samenwerking" },
      { value: "pers", label: "Pers" },
      { value: "juridisch", label: "Juridisch / compliance" },
      { value: "overig", label: "Overig" },
    ],
    subjectPlaceholder: draft("Kies een onderwerp"),
    consent: draft("Ik ga akkoord met de verwerking van mijn gegevens volgens het"),
    consentLink: "Privacybeleid",
    submit: "Stuur bericht",
    sending: draft("Versturen…"),
    success: "Bedankt. We nemen persoonlijk contact met je op.",
    errors: {
      required: "Dit veld is verplicht.",
      email: "Vul een geldig e-mailadres in.",
      consent: draft("Ga akkoord met het privacybeleid om het bericht te versturen."),
      tooLong: draft("Dit veld is te lang."),
      rateLimited: draft("Te veel berichten in korte tijd. Probeer het later opnieuw."),
      failed: draft("Het bericht kon niet worden verstuurd. Probeer het later opnieuw of stuur een e-mail."),
    },
  },
  about: {
    title: "Over ons",
    promiseLabel: draft("Belofte"),
    promise: "Van oud naar waardevol",
    managementTitle: "Bestuur",
  },
  legal: {
    lastUpdated: "Laatst bijgewerkt",
    placeholderNote: "Placeholder: definitieve tekst volgt van legal.",
  },
  footer: {
    links: [
      { key: "privacy", label: "Privacybeleid" },
      { key: "cookies", label: "Cookiebeleid" },
      { key: "disclaimer", label: "Disclaimer" },
      { key: "colophon", label: "Colofon" },
    ],
    copyright: (year) => `© ${year}`,
    kvk: "KvK",
    vat: "BTW",
    linkedin: "LinkedIn",
    // Contactband: DESIGN §10.1 (7. Contact) letterlijk
    cta: { label: "Contact", title: "Neem contact op", body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.", button: "Neem contact op" },
    callUs: draft("Bel ons"),
    backToTop: draft("Naar boven"),
  },
  notFound: { title: "Deze pagina bestaat niet (meer)", home: draft("Terug naar de homepage") },
  placeholders: {
    description: "Placeholder: geverifieerde bedrijfsomschrijving (2–3 zinnen) volgt van Supreme.",
    story: "Placeholder: kort, geverifieerd bedrijfsverhaal volgt van Supreme.",
    media: "Placeholder: gelicentieerde fotografie volgt.",
    film: "Placeholder: herofilm en poster volgen van de filmmaker.",
    credits: "Placeholder: foto- en filmcredits volgen van Supreme.",
    // Fictional stand-ins for the header menu (owner's request 2026-10-01); replaced by company.json once verified.
    address: [draft("Voorbeeldstraat 12"), draft("1000 AA Amsterdam")],
    phone: draft("+31 20 000 00 00"),
    social: [draft("LinkedIn"), draft("Instagram"), draft("Facebook")],
  },
};
