import type { Copy } from "./copy.types";
import { draft } from "./draft";

export const en: Copy = {
  siteName: "Supreme Real Estate",
  meta: {
    homeTitle: "Supreme Real Estate · From old to valuable",
    titlePattern: (page) => `${page} · Supreme Real Estate`,
    description: "Supreme Real Estate is a real-estate company in Amsterdam, focused on existing homes and the long term.",
    pages: {
      about: { title: "About", description: draft("About Supreme Real Estate: what we stand for and our company details.") },
      contact: { title: "Contact", description: draft("Get in touch with Supreme Real Estate for partnerships, press or other questions.") },
      privacy: { title: "Privacy policy", description: draft("Privacy policy of Supreme Real Estate.") },
      cookies: { title: "Cookie policy", description: draft("Cookie policy of Supreme Real Estate.") },
      disclaimer: { title: "Disclaimer", description: draft("Disclaimer of Supreme Real Estate.") },
      colophon: { title: "Colophon", description: draft("Colophon of Supreme Real Estate: company details and credits.") },
    },
    notFoundTitle: "This page does not exist (anymore)",
  },
  a11y: {
    skip: draft("Skip to content"),
    languageSwitch: draft("Language"),
    nl: "Nederlands",
    en: "English",
    mainNav: draft("Main menu"),
    footerNav: draft("Legal"),
    legalNav: draft("Legal pages"),
    home: draft("Supreme Real Estate, to the homepage"),
  },
  nav: {
    about: "About",
    contact: "Contact",
    menu: draft("Navigate to"),
    switchTo: draft("Naar het Nederlands"),
    closeMenu: "Close menu",
    contactUs: draft("Contact us"),
    // Section by section (owner's note 2026-10-01); grows with the homepage
    sections: [
      { id: "home", label: draft("Home") },
      { id: "about", label: "About" },
      { id: "approach", label: draft("How we work") },
      { id: "work", label: draft("Projects") },
    ],
  },
  brand: { wordmark: "SUPREME", descriptor: "REAL ESTATE", tagline: "From old to valuable" },
  hero: {
    // Hero concept 2026-09-30 (owner-supplied). Approved brand promise "From old to valuable." stays in the docs.
    headline: draft("Beyond\nSpaces for Living"),
    keyMessage: draft("Creating value through property and perspective."),
    pause: "Pause video",
    play: "Play video",
  },
  // Shelf statement: owner concept 2026-09-30 (draft until approved).
  shelf: {
    parts: [draft("We unlock the potential of existing"), { icon: "bulb" }, draft("properties, transforming"), { icon: "hammer" }, draft("them into thoughtfully designed homes and continuing to manage"), { icon: "clipboard" }, draft("their value over time"), { icon: "chart" }],
  },
  // About + company details (owner, 2026-10-07; copy from the section-drafts doc, rewritten from supremerealestate.nl/over-ons).
  aboutStory: {
    label: "About",
    title: "From old to valuable.",
    chapters: [
      { name: draft("Why"), body: draft("The Netherlands needs homes, and the Amsterdam region is full of buildings that could be more. Supreme Real Estate closes that gap: not by building new, but by giving existing property a second life.") },
      { name: draft("What we do"), body: draft("We acquire buildings that have seen better days: old offices, large houses, properties with overdue maintenance. We redevelop them into independent, turnkey homes in good locations in and around Amsterdam.") },
      { name: draft("Design"), body: draft("Every design starts with the future resident. A home should feel warm, be full of light and last. 3D visualisations show a space before it is built; good proportions, durable materials and clean lines do the rest.") },
      { name: draft("Realisation"), body: draft("We build with a fixed contractor and a fixed design and build team. That brings calm in a tight construction market: short lines, a tight but flexible schedule and involvement from the first sketch to the final finish.") },
      { name: draft("Delivery"), body: draft("From purchase, design and permit to installation and finishing: every step in our own hands. After a few weeks of building work a turnkey apartment stands ready, and the region gains one more home.") },
    ],
    close: draft("We are open to working with professionals, brokers and municipalities who share the same ambition."),
    // stage lines and finale: the user's 1 building → 8 homes brief (2026-10-07), verbatim where it gives them
    stages: [
      { label: draft("Existing"), title: "One building.", chapter: 0 },
      { label: draft("Potential"), title: "More potential than meets the eye.", chapter: 1 },
      { label: draft("Redevelop"), title: draft("Eight independent apartments."), chapter: 2 },
      { label: draft("Homes"), title: draft("Eight new homes."), chapter: 3 },
      { label: draft("Value"), title: "Giving existing property a second life.", chapter: null },
    ],
    finale: { title: "One property. Eight homes.", body: "We unlock the potential of existing properties, thoughtfully transforming them into lasting homes." },
  },
  register: {
    label: draft("Company"),
    salutation: draft("To whom it may concern,"),
    // owner's wording (2026-10-07)
    lead: "Supreme Real Estate B.V. is registered with the Dutch Chamber of Commerce (KvK). The details below correspond with its official business registration.",
    verify: draft("Check in the KvK register"),
    signoff: draft("Kind regards,"),
    pending: "Placeholder: KvK number, VAT number, visiting address and contact details to follow from the KvK extract.",
  },

  // Steps: owner concept 2026-10-01 (three steps verbatim from the owner's mock-up; headline lines draft).
  steps: {
    label: draft("Reimagining value"),
    lines: [draft("Unlocking potential."), draft("Transforming properties."), draft("Creating lasting value.")],
    items: [
      { index: "01", title: draft("Reimagine"), body: draft("Understanding the existing property and its potential.") },
      { index: "02", title: draft("Divide"), body: draft("Transforming larger spaces into independent homes.") },
      { index: "03", title: draft("Deliver"), body: draft("Completing each apartment as a turnkey living experience.") },
    ],
  },
  // Sky band: owner concept 2026-10-01 (drafts until approved). The seventh card completes the arc.
  // Projects: concept 2026-10-02, anonymised cases, all EN draft until approved.
  work: {
    // the collaboration ring's headline (owner, 2026-10-07: about the partners on the cards, not the projects)
    intro: [draft("Built together"), draft("with people"), draft("we trust.")],
    label: draft("What we deliver"),
    title: draft("A selection, from old to valuable."),
    cta: draft("Request the documentation"),
    items: [
      {
        index: "01",
        title: draft("A farmstead in the polder, reimagined"),
        body: draft("A former livestock farm by the water on the edge of Amsterdam, in open polder land. The plan: a country home that keeps the calm of the landscape around it."),
        note: draft("A render of the living room to come; the plot and the polder from the air."),
      },
      {
        index: "02",
        title: draft("A townhouse in the heart of Haarlem"),
        body: draft("A characterful townhouse with a rear coach house, restored with care: tall rooms, wooden floors and the light of tall windows, made ready for the long term."),
        note: draft("A tall living room with a chandelier; the living and dining floor under a skylight."),
      },
      {
        index: "03",
        title: draft("Homes above the shop, under one renewed roof"),
        body: draft("A mixed-use building in Haarlem, redeveloped into independent apartments above a shop. Bright kitchens, oak floors and calm bathrooms, finished to last."),
        note: draft("Kitchen with an island, living room with stained-glass windows, bathroom with a round mirror."),
      },
      {
        index: "04",
        title: draft("Room to breathe, from shell to turnkey"),
        body: draft("Generous rooms given back their proportions. An open kitchen on the living room, a calm bathroom and a bedroom with a view, delivered turnkey as a place to live."),
        note: draft("Kitchen with a brass tap, bathroom with a black basin, bedroom with a large window."),
      },
    ],
  },
  // Project windows: concept 2026-10-05. Names, cities and categories from the owner; descriptions are drafts.
  projects: {
    hotspot: (name) => `Explore ${name}`,
    eyebrow: "Project",
    explore: draft("Explore project"),
    back: draft("Back to overview"),
    more: draft("Explore more"),
    index: draft("Projects"),
    country: "Netherlands",
    categories: { residential: draft("Residential"), mixed: draft("Mixed-use") },
    page: {
      credits: {
        developer: draft("Developer"),
        architect: draft("Architect"),
        builder: draft("Builder"),
        interior: draft("Interior design"),
        photography: draft("Photography"),
        location: draft("Location"),
        category: draft("Category"),
        pending: draft("To be confirmed"),
      },
      overview: draft("Overview"),
      details: draft("Project details"),
      scroll: draft("Scroll down"),
      chapters: { opportunity: draft("The opportunity"), approach: draft("Our approach"), outcome: draft("The outcome"), why: draft("Why it matters") },
      compare: {
        title: draft("Before and after"),
        before: draft("Before"),
        after: draft("After"),
        hint: draft("Drag to compare"),
        slider: (room) => draft(`Compare before and after: ${room}`),
      },
      rooms: { kitchen: draft("Kitchen"), living: draft("Living floor"), attic: draft("Roof space"), roof: draft("Roof") },
      gallery: {
        title: draft("Photos"),
        count: (n) => draft(`${n} photos`),
        open: (i, n) => draft(`Open photo ${i} of ${n}`),
        counter: (i, n) => `${i} / ${n}`,
        close: draft("Close photos"),
        prev: draft("Previous photo"),
        next: draft("Next photo"),
      },
      others: draft("Other projects"),
      view: draft("View project"),
    },
    // Prinsen Bolwerk: the owner's own example (2026-10-06), verbatim. The other three follow its shape as drafts:
    // generic on purpose (no facts beyond name, city and category) until the owner writes them.
    items: {
      durgerdammergouw: {
        title: draft("Country home — Amsterdam"),
        lede: draft("A former livestock farm in the polder, reimagined as a home."),
        opportunity: draft("On the edge of Amsterdam, a former livestock farm in open polder land: a rare plot by the water, with room to make something lasting."),
        approach: draft("Supreme leads the redevelopment: a plan for a country home that fits the landscape, made with the right architects and specialists."),
        outcome: draft("A home designed around its setting and held for the long term within Supreme's managed portfolio."),
        why: draft("The right plot, treated with care: a new home that belongs to the landscape it stands in."),
      },
      "prinsen-bolwerk": {
        title: draft("Historic townhouse — Haarlem"),
        lede: draft("Restoring a city-centre landmark into high-quality homes."),
        opportunity: draft("In the heart of Haarlem, a characterful townhouse with a rear coach house — full of potential, but in need of careful redevelopment."),
        approach: draft("Supreme acquired the property and led a sensitive restoration: securing the right permissions, reconfiguring the layout into independent homes, and renovating to a high, contemporary standard while preserving its historic character."),
        outcome: draft("Delivered as high-quality residences and retained within Supreme's managed portfolio — held for the long term."),
        why: draft("A clear example of how we work: identify characterful properties, transform them with care and the right expertise, and manage them for the long term."),
      },
      schoterweg: {
        title: draft("Mixed-use building — Haarlem"),
        lede: draft("Homes and workspace, brought together under one renewed roof."),
        opportunity: draft("In Haarlem, an existing building with room to do more: space for living and for work, under one roof."),
        approach: draft("Supreme took on the redevelopment: planning homes and workspace that work side by side, securing the right permissions, and renovating to a high, contemporary standard."),
        outcome: draft("Delivered as a mix of homes and workspace and retained within Supreme's managed portfolio — held for the long term."),
        why: draft("Mixed use, done with care: one building that serves more people, managed with the same attention as on the first day."),
      },
      bezaanjachtplein: {
        title: draft("City apartments — Amsterdam"),
        lede: draft("Renewing existing apartments into ready-to-live homes."),
        opportunity: draft("In Amsterdam, existing apartments with sound foundations and interiors that had had their day."),
        approach: draft("Supreme renewed them from the inside: a lighter layout, new kitchens and bathrooms, and finishes chosen to last."),
        outcome: draft("Delivered as ready-to-live homes and retained within Supreme's managed portfolio — held for the long term."),
        why: draft("Good homes stay good when someone looks after them: renewed with care, managed for the long term."),
      },
    },
  },
  sky: {
    label: draft("From"),
    title: draft("Potential to Turnkey"),
    lead: draft("We transform existing properties into thoughtfully designed, ready-to-live spaces."),
    ctaPrimary: draft("Explore our approach"),
    ctaSecondary: draft("View projects"),
    // Seven cards, far left to far right (owner's order); the outer two are the property as found and as finished
    cards: [
      { title: draft("Property"), body: draft("Existing") },
      { title: draft("Acquire"), body: draft("Existing properties with potential") },
      { title: draft("Reimagined"), body: draft("A new vision for valuable spaces") },
      { title: draft("Transformed"), body: draft("Thoughtful development and high-quality design") },
      { title: draft("Refined"), body: draft("Modern living with timeless details") },
      { title: draft("Turnkey"), body: draft("Ready-to-live homes, completed to a high standard") },
      { title: draft("Property"), body: draft("Completed") },
    ],
  },
  statement: {
    label: draft("01 — Supreme"),
    text: "We see what a home can become, and give it a new future with care. Carefully chosen, renewed with craft, for the long term.",
    aside: draft("No quick transactions. We work with a horizon of decades, in the city we call home."),
  },
  principles: {
    label: draft("02 — Principles"),
    title: "What we stand for",
    sub: draft("Three principles behind every decision."),
    items: [
      { index: "01", title: "Careful", body: "We choose with attention and work with people who deliver craftsmanship." },
      { index: "02", title: "Lasting", body: "What we renew should last for generations." },
      { index: "03", title: "Long term", body: "We think in decades, not in transactions." },
    ],
  },
  carousel: {
    label: draft("03 — Details"),
    title: "Material, light and space",
    sub: draft("What lasts begins with what you touch and see."),
    items: [
      { title: draft("Material"), body: draft("Lime, stone, oak and brass. Materials that grow more beautiful with time.") },
      { title: draft("Light"), body: draft("Daylight as a building material: high, soft and present all day.") },
      { title: draft("Space"), body: draft("Space that gives calm, with measure and proportion that feel right.") },
    ],
  },
  map: {
    label: draft("04 — Amsterdam"),
    title: draft("At home in Amsterdam"),
    sub: draft("We work in the city we call home, with respect for what already stands."),
    cta: "About Supreme",
    dot: "Amsterdam",
  },
  closing: {
    title: draft("Made to last"),
    body: "For partnerships, press or other questions: we reply personally.",
    cta: "Get in touch",
    marquee: "From old to valuable",
  },
  details: {
    label: draft("03 — Details"),
    title: "Material, light and space",
    counter: (i, n) => `${i} / ${n}`,
    scrollerLabel: draft("Images of material, light and space"),
  },
  companySection: { label: draft("04 — Company"), title: "Company details" },
  companyKeys: {
    legalName: draft("Legal name"),
    tradeName: draft("Trade name"),
    kvk: "KvK number", // owner, 2026-10-07
    visitingAddress: draft("Visiting address"),
    postalAddress: draft("Postal address"),
    vat: draft("VAT number"),
    email: draft("Email"),
    emailLegal: draft("Email (legal)"),
    phone: draft("Phone"),
    availability: draft("Availability"),
    management: draft("Management"),
    linkedin: "LinkedIn",
  },
  companyLegalLine: "For legal or compliance questions",
  contactSection: {
    label: draft("05 — Contact"),
    title: "Get in touch",
    body: "For partnerships, press or other questions: we reply personally.",
    cta: "Get in touch",
  },
  contactPage: {
    title: "Contact",
    lead: "For partnerships, press or other questions: we reply personally.",
    methodsTitle: draft("Reach us"),
    formTitle: draft("Send a message"),
  },
  form: {
    name: draft("Name"),
    organisation: draft("Organisation"),
    email: draft("Email"),
    phone: draft("Phone"),
    subject: draft("Subject"),
    message: draft("Message"),
    optional: draft("optional"),
    subjects: [
      { value: "samenwerking", label: draft("Partnership") },
      { value: "pers", label: draft("Press") },
      { value: "juridisch", label: draft("Legal / compliance") },
      { value: "overig", label: draft("Other") },
    ],
    subjectPlaceholder: draft("Choose a subject"),
    consent: draft("I agree to the processing of my data according to the"),
    consentLink: "Privacy policy",
    submit: "Send message",
    sending: draft("Sending…"),
    success: "Thank you. We will contact you personally.",
    errors: {
      required: "This field is required.",
      email: "Enter a valid email address.",
      consent: draft("Agree to the privacy policy to send the message."),
      tooLong: draft("This field is too long."),
      rateLimited: draft("Too many messages in a short time. Please try again later."),
      failed: draft("The message could not be sent. Please try again later or send an email."),
    },
  },
  about: {
    title: "About",
    promiseLabel: draft("Promise"),
    promise: "From old to valuable",
    managementTitle: draft("Management"),
  },
  legal: {
    lastUpdated: draft("Last updated"),
    placeholderNote: "Placeholder: final text to follow from legal.",
  },
  footer: {
    links: [
      { key: "privacy", label: "Privacy policy" },
      { key: "cookies", label: "Cookie policy" },
      { key: "disclaimer", label: "Disclaimer" },
      { key: "colophon", label: "Colophon" },
    ],
    copyright: (year) => `© ${year}`,
    kvk: "KvK",
    vat: draft("VAT"),
    linkedin: "LinkedIn",
    // Contact band: DESIGN §10.1 (7. Contact) verbatim
    cta: { label: "Contact", title: "Get in touch", body: "For partnerships, press or other questions: we reply personally.", button: "Get in touch" },
    mailUs: draft("Email us"),
    backToTop: draft("Back to top"),
  },
  notFound: { title: "This page does not exist (anymore)", home: draft("Back to the homepage") },
  placeholders: {
    description: "Placeholder: verified company description (2–3 sentences) to follow from Supreme.",
    story: "Placeholder: short, verified company story to follow from Supreme.",
    media: "Placeholder: licensed photography to follow.",
    film: "Placeholder: hero film and poster to follow from the film maker.",
    credits: "Placeholder: photo and film credits to follow from Supreme.",
    // Fictional stand-ins for the header menu (owner's request 2026-10-01); replaced by company.json once verified.
    address: [draft("Example street 12"), draft("1000 AA Amsterdam")],
    phone: draft("+31 20 000 00 00"),
    social: [draft("LinkedIn"), draft("Instagram"), draft("Facebook")],
  },
};
