import type { Copy } from "./copy.types";
import { draft } from "./draft";

export const nl: Copy = {
  siteName: "Supreme Real Estate",
  meta: {
    homeTitle: "Supreme Real Estate · Van oud naar waardevol",
    titlePattern: (page) => `${page} · Supreme Real Estate`,
    description: "Supreme Real Estate is een vastgoedonderneming in Amsterdam, gericht op bestaande woningen en de lange termijn.",
    pages: {
      about: { title: "Over ons", description: draft("Over Supreme Real Estate: waar wij voor staan en onze bedrijfsgegevens.") },
      contact: { title: "Contact", description: draft("Neem contact op met Supreme Real Estate voor samenwerking, pers of andere vragen.") },
      privacy: { title: "Privacybeleid", description: draft("Privacybeleid van Supreme Real Estate.") },
      cookies: { title: "Cookiebeleid", description: draft("Cookiebeleid van Supreme Real Estate.") },
      disclaimer: { title: "Disclaimer", description: draft("Disclaimer van Supreme Real Estate.") },
      colophon: { title: "Colofon", description: draft("Colofon van Supreme Real Estate: bedrijfsgegevens en credits.") },
    },
    notFoundTitle: "Deze pagina bestaat niet (meer)",
  },
  a11y: {
    skip: draft("Naar inhoud"),
    languageSwitch: draft("Taal"),
    nl: "Nederlands",
    en: "English",
    mainNav: draft("Hoofdmenu"),
    footerNav: draft("Juridisch"),
    legalNav: draft("Juridische pagina's"),
    home: draft("Supreme Real Estate, naar de homepage"),
  },
  nav: {
    about: "Over ons",
    contact: "Contact",
    menu: draft("Navigeer naar"),
    switchTo: draft("Switch to English"),
    closeMenu: "Sluit menu",
    contactUs: "Neem contact op",
    sections: [
      { id: "home", label: draft("Home") },
      { id: "about", label: "Over ons" },
      { id: "approach", label: draft("Werkwijze") },
      { id: "work", label: draft("Projecten") },
    ],
  },
  brand: { wordmark: "SUPREME", descriptor: "REAL ESTATE", tagline: "Van oud naar waardevol" },
  hero: {
    // Hero concept 2026-09-30 (owner-supplied English copy, NL draft). The approved brand promise
    // "Van oud naar waardevol." stays in the docs; restore it here if the concept copy is not approved.
    headline: draft("Meer dan ruimte\nom te wonen"),
    keyMessage: draft("Waarde creëren door vastgoed en visie."),
    pause: "Pauzeer video",
    play: "Speel video af",
  },
  // Shelf statement: owner concept 2026-09-30, NL draft until approved.
  shelf: {
    parts: [draft("Wij zien de mogelijkheden van bestaande"), { icon: "bulb" }, draft("panden, vernieuwen"), { icon: "hammer" }, draft("ze tot zorgvuldig ontworpen woningen en blijven"), { icon: "clipboard" }, draft("hun waarde beheren, jaar na jaar"), { icon: "chart" }],
  },
  // About + company details (owner, 2026-10-07; copy from the section-drafts doc, rewritten from supremerealestate.nl/over-ons).
  aboutStory: {
    label: "Over ons",
    title: "Van oud naar waardevol.",
    chapters: [
      { name: draft("Waarom"), body: draft("Nederland heeft woningen nodig, en de regio Amsterdam staat vol gebouwen die meer kunnen zijn. Supreme Real Estate maakt dat verschil: niet door nieuw te bouwen, maar door bestaand vastgoed een tweede leven te geven.") },
      { name: draft("Wat we doen"), body: draft("We kopen panden die hun beste tijd achter zich hebben: oude kantoren, grote woningen, gebouwen met achterstallig onderhoud. Die ontwikkelen we opnieuw tot zelfstandige, sleutelklare woningen op goede plekken in en rond Amsterdam.") },
      { name: draft("Ontwerp"), body: draft("Elk ontwerp begint bij de toekomstige bewoner. Een huis moet warm voelen, licht zijn en lang meegaan. Met 3D-visualisaties zien we vooraf hoe een ruimte wordt; goede verhoudingen, duurzame materialen en strakke lijnen doen de rest.") },
      { name: draft("Realisatie"), body: draft("We bouwen met een vaste aannemer en een vast design- en bouwteam. Dat geeft rust in een krappe bouwmarkt: korte lijnen, een strakke maar flexibele planning en betrokkenheid van de eerste schets tot de laatste afwerking.") },
      { name: draft("Oplevering"), body: draft("Van aankoop, ontwerp en vergunning tot installatie en afbouw: elke stap in eigen hand. Na enkele weken verbouwen staat er een sleutelklaar appartement, en zo krijgt de regio er steeds weer een woning bij.") },
    ],
    close: draft("We staan open voor samenwerking met vakmensen, makelaars en gemeenten die dezelfde ambitie delen."),
    stages: [
      { label: draft("Bestaand"), title: draft("Bestaand vastgoed."), chapter: 0 },
      { label: draft("Potentie"), title: draft("Potentie, klaar om ontsloten te worden."), chapter: 1 },
      { label: draft("Herontwikkeling"), title: draft("Zorgvuldig getransformeerd."), chapter: null },
      { label: draft("Ontwerp"), title: draft("Ontworpen rond de toekomstige bewoner."), chapter: 2 },
      { label: draft("Realisatie"), title: draft("Van eerste schets tot laatste afwerking."), chapter: 3 },
      { label: draft("Oplevering"), title: draft("Weer een woning erbij in de regio."), chapter: 4 },
    ],
  },
  register: {
    label: draft("Bedrijf"),
    salutation: draft("Aan wie het aangaat,"),
    lead: draft("Supreme Real Estate B.V. is ingeschreven bij de Kamer van Koophandel (KvK). De onderstaande gegevens komen overeen met de officiële inschrijving in het Handelsregister."),
    verify: draft("Controleer in het KvK-register"),
    signoff: draft("Met vriendelijke groet,"),
    pending: "Placeholder: KvK-nummer, BTW-nummer, vestigingsadres en contactgegevens volgen uit het KvK-uittreksel.",
  },

  // Steps: owner concept 2026-10-01, NL draft until approved.
  steps: {
    label: draft("Waarde opnieuw bekeken"),
    lines: [draft("Potentieel ontsluiten."), draft("Panden transformeren."), draft("Blijvende waarde creëren.")],
    items: [
      { index: "01", title: draft("Herzien"), body: draft("Begrijpen wat een bestaand pand is en kan worden.") },
      { index: "02", title: draft("Verdelen"), body: draft("Grotere ruimtes omvormen tot zelfstandige woningen.") },
      { index: "03", title: draft("Opleveren"), body: draft("Elke woning turnkey opleveren als een plek om te wonen.") },
    ],
  },
  // Projects: concept 2026-10-02, anonymised cases, all NL draft until approved.
  work: {
    // the collaboration ring's headline (owner, 2026-10-07: about the partners on the cards, not the projects)
    intro: [draft("Samen gebouwd"), draft("met mensen"), draft("die we vertrouwen.")],
    label: draft("Wat wij opleveren"),
    title: draft("Een selectie, van oud naar waardevol."),
    cta: draft("Vraag de documentatie aan"),
    items: [
      {
        index: "01",
        title: draft("Een woning, opnieuw ingedeeld rond het licht"),
        body: draft("Een bestaande woning waarvan de plattegrond niet meer paste bij hoe er gewoond wordt. Wij hebben de indeling herzien rond een lichte woonkeuken en elke ruimte een duidelijke functie gegeven."),
        note: draft("Woonkeuken met kookeiland, slaapkamer onder een dakraam, badkamer met zwarte wastafels."),
      },
      {
        index: "02",
        title: draft("Donker hout en warm licht op een compacte plattegrond"),
        body: draft("Een compacte woning waarin elke centimeter telt. Een hoge keukenwand in donker hout, messing details en een rustige badkamer maken van weinig ruimte een volwassen woning."),
        note: draft("Keuken met houten bar, messing kraan bij een ronde spiegel, woonkamer met brede ramen."),
      },
      {
        index: "03",
        title: draft("Steen, messing en een slaapkamer onder het dak"),
        body: draft("Een pand waarin de zolder jarenlang ongebruikt bleef. De verdieping is bij de woning getrokken en afgewerkt in natuursteen en messing: materialen die mooier worden met de tijd."),
        note: draft("Keuken met marmeren werkblad, badkamer in natuursteen, slaapkamer onder het dak."),
      },
      {
        index: "04",
        title: draft("Ruimte om te ademen, van casco tot instapklaar"),
        body: draft("Royale kamers die hun maat terugkregen. Een open keuken aan de woonkamer, een rustige badkamer en een slaapkamer met uitzicht, turnkey opgeleverd als een plek om te wonen."),
        note: draft("Woonkamer met open keuken, badkamer met ronde spiegel, slaapkamer met uitzicht."),
      },
    ],
  },
  // Project windows: concept 2026-10-05. Names, cities and categories from the owner; descriptions are drafts.
  projects: {
    hotspot: (name) => `Bekijk ${name}`,
    eyebrow: "Project",
    explore: draft("Bekijk het project"),
    back: draft("Terug naar het overzicht"),
    more: draft("Meer projecten"),
    index: draft("Projecten"),
    country: "Nederland",
    categories: { residential: draft("Wonen"), mixed: draft("Gemengd") },
    page: {
      credits: {
        developer: draft("Ontwikkelaar"),
        architect: draft("Architect"),
        builder: draft("Aannemer"),
        interior: draft("Interieur"),
        photography: draft("Fotografie"),
        location: draft("Locatie"),
        category: draft("Categorie"),
        pending: draft("Volgt"),
      },
      overview: draft("Overzicht"),
      details: draft("Projectdetails"),
      scroll: draft("Scroll naar beneden"),
      chapters: { opportunity: draft("De kans"), approach: draft("Onze aanpak"), outcome: draft("Het resultaat"), why: draft("Waarom het ertoe doet") },
      compare: {
        title: draft("Voor en na"),
        before: draft("Voor"),
        after: draft("Na"),
        hint: draft("Sleep om te vergelijken"),
        slider: (room) => draft(`Vergelijk voor en na: ${room}`),
      },
      rooms: { kitchen: draft("Keuken"), living: draft("Woonverdieping"), attic: draft("Zolder"), roof: draft("Kap") },
      gallery: {
        title: draft("Foto's"),
        count: (n) => draft(`${n} foto's`),
        open: (i, n) => draft(`Open foto ${i} van ${n}`),
        counter: (i, n) => `${i} / ${n}`,
        close: draft("Foto's sluiten"),
        prev: draft("Vorige foto"),
        next: draft("Volgende foto"),
      },
      others: draft("Andere projecten"),
      view: draft("Bekijk project"),
    },
    // Prinsen Bolwerk: vertaling van het voorbeeld van de eigenaar (2026-10-06). De andere drie volgen die vorm als
    // concept: bewust algemeen (geen feiten naast naam, stad en categorie) tot de eigenaar ze schrijft.
    items: {
      durgerdammergouw: {
        title: draft("Woningrenovatie — Amsterdam"),
        lede: draft("Een bestaand huis, vernieuwd tot rustige, eigentijdse woningen."),
        opportunity: draft("In Amsterdam: een bestaand huis met een goede basis en een gedateerd interieur. Het behouden waard, klaar voor een nieuw hoofdstuk."),
        approach: draft("Supreme nam de herontwikkeling op zich: een helder plan voor de indeling, de juiste vakmensen voor elk onderdeel en een renovatie tot een hoog, eigentijds niveau."),
        outcome: draft("Opgeleverd als hoogwaardige woningen en behouden in de door Supreme beheerde portefeuille — voor de lange termijn."),
        why: draft("Rustig, zorgvuldig werk: het juiste pand, goed vernieuwd en jarenlang met aandacht beheerd."),
      },
      "prinsen-bolwerk": {
        title: draft("Historisch herenhuis — Haarlem"),
        lede: draft("Een markant pand in de binnenstad, gerestaureerd tot hoogwaardige woningen."),
        opportunity: draft("In het hart van Haarlem: een karaktervol herenhuis met een koetshuis aan de achterzijde — vol potentie, maar toe aan een zorgvuldige herontwikkeling."),
        approach: draft("Supreme verwierf het pand en leidde een behoedzame restauratie: de juiste vergunningen geregeld, de indeling omgezet naar zelfstandige woningen en gerenoveerd tot een hoog, eigentijds niveau, met behoud van het historische karakter."),
        outcome: draft("Opgeleverd als hoogwaardige woningen en behouden in de door Supreme beheerde portefeuille — voor de lange termijn."),
        why: draft("Een helder voorbeeld van hoe wij werken: karaktervolle panden vinden, ze met zorg en de juiste expertise transformeren en ze voor de lange termijn beheren."),
      },
      schoterweg: {
        title: draft("Wonen en werken — Haarlem"),
        lede: draft("Woningen en werkruimte, samengebracht onder één vernieuwd dak."),
        opportunity: draft("In Haarlem: een bestaand pand met ruimte voor meer. Plek om te wonen en te werken, onder één dak."),
        approach: draft("Supreme nam de herontwikkeling op zich: woningen en werkruimte die naast elkaar functioneren, de juiste vergunningen en een renovatie tot een hoog, eigentijds niveau."),
        outcome: draft("Opgeleverd als een mix van woningen en werkruimte en behouden in de door Supreme beheerde portefeuille — voor de lange termijn."),
        why: draft("Gemengd gebruik, met zorg gedaan: één pand dat meer mensen dient, beheerd met dezelfde aandacht als op de eerste dag."),
      },
      bezaanjachtplein: {
        title: draft("Stadsappartementen — Amsterdam"),
        lede: draft("Bestaande appartementen, vernieuwd tot instapklare woningen."),
        opportunity: draft("In Amsterdam: bestaande appartementen met een gezonde basis en een interieur dat zijn tijd had gehad."),
        approach: draft("Supreme vernieuwde ze van binnenuit: een lichtere indeling, nieuwe keukens en badkamers en afwerking die lang meegaat."),
        outcome: draft("Opgeleverd als instapklare woningen en behouden in de door Supreme beheerde portefeuille — voor de lange termijn."),
        why: draft("Goede woningen blijven goed als iemand ze onderhoudt: met zorg vernieuwd, voor de lange termijn beheerd."),
      },
    },
  },
  // Sky band: owner concept 2026-10-01, NL draft until approved.
  sky: {
    label: draft("Van"),
    title: draft("Potentieel naar turnkey"),
    lead: draft("Wij transformeren bestaande panden tot zorgvuldig ontworpen, instapklare woningen."),
    ctaPrimary: draft("Onze werkwijze"),
    ctaSecondary: draft("Bekijk projecten"),
    cards: [
      { title: draft("Pand"), body: draft("Bestaand") },
      { title: draft("Verwerven"), body: draft("Bestaande panden met potentieel") },
      { title: draft("Herzien"), body: draft("Een nieuwe visie op waardevolle ruimte") },
      { title: draft("Getransformeerd"), body: draft("Zorgvuldige ontwikkeling en hoogwaardig ontwerp") },
      { title: draft("Verfijnd"), body: draft("Modern wonen met tijdloze details") },
      { title: draft("Turnkey"), body: draft("Instapklare woningen, afgewerkt op hoog niveau") },
      { title: draft("Pand"), body: draft("Opgeleverd") },
    ],
  },
  statement: {
    label: "01 — Supreme",
    text: "Wij zien wat een woning kan worden, en geven haar met zorg een nieuwe toekomst. Zorgvuldig gekozen, met vakmanschap vernieuwd, voor de lange termijn.",
    aside: draft("Geen snelle transacties. Wij werken met een horizon van decennia, in de stad waar we thuis zijn."),
  },
  principles: {
    label: "02 — Principes",
    title: "Waar wij voor staan",
    sub: draft("Drie principes achter elke keuze."),
    items: [
      { index: "01", title: "Zorgvuldig", body: "Wij kiezen met aandacht en werken met mensen die vakmanschap leveren." },
      { index: "02", title: "Blijvend", body: "Wat wij vernieuwen, moet generaties meegaan." },
      { index: "03", title: "Lange termijn", body: "Wij denken in decennia, niet in transacties." },
    ],
  },
  carousel: {
    label: "03 — Details",
    title: "Materiaal, licht en ruimte",
    sub: draft("Wat blijft, begint bij wat je aanraakt en ziet."),
    items: [
      { title: draft("Materiaal"), body: draft("Kalk, steen, eik en messing. Materialen die mooier worden met de tijd.") },
      { title: draft("Licht"), body: draft("Daglicht als bouwmateriaal: hoog, zacht en de hele dag aanwezig.") },
      { title: draft("Ruimte"), body: draft("Ruimte die rust geeft, met maat en proportie die kloppen.") },
    ],
  },
  map: {
    label: draft("04 — Amsterdam"),
    title: draft("Thuis in Amsterdam"),
    sub: draft("Wij werken in de stad waar we thuis zijn, met respect voor wat er al staat."),
    cta: "Over Supreme",
    dot: "Amsterdam",
  },
  closing: {
    title: draft("Gemaakt om te blijven"),
    body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    cta: "Neem contact op",
    marquee: "Van oud naar waardevol",
  },
  details: {
    label: "03 — Details",
    title: "Materiaal, licht en ruimte",
    counter: (i, n) => `${i} / ${n}`,
    scrollerLabel: draft("Beelden van materiaal, licht en ruimte"),
  },
  companySection: { label: draft("04 — Bedrijf"), title: "Bedrijfsgegevens" },
  companyKeys: {
    legalName: "Statutaire naam",
    tradeName: "Handelsnaam",
    kvk: "KvK-nummer",
    visitingAddress: "Vestigingsadres",
    postalAddress: "Postadres",
    vat: "BTW-nummer",
    email: "E-mail",
    emailLegal: draft("E-mail (juridisch)"),
    phone: "Telefoon",
    availability: "Bereikbaar",
    management: "Bestuur",
    linkedin: "LinkedIn",
  },
  companyLegalLine: "Voor juridische of compliance-vragen",
  contactSection: {
    label: draft("05 — Contact"),
    title: "Neem contact op",
    body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    cta: "Neem contact op",
  },
  contactPage: {
    title: "Contact",
    lead: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.",
    methodsTitle: draft("Bereik ons"),
    formTitle: draft("Stuur een bericht"),
  },
  form: {
    name: "Naam",
    organisation: "Organisatie",
    email: "E-mail",
    phone: "Telefoon",
    subject: "Onderwerp",
    message: "Bericht",
    optional: "optioneel",
    subjects: [
      { value: "samenwerking", label: "Samenwerking" },
      { value: "pers", label: "Pers" },
      { value: "juridisch", label: "Juridisch / compliance" },
      { value: "overig", label: "Overig" },
    ],
    subjectPlaceholder: draft("Kies een onderwerp"),
    consent: draft("Ik ga akkoord met de verwerking van mijn gegevens volgens het"),
    consentLink: "Privacybeleid",
    submit: "Stuur bericht",
    sending: draft("Versturen…"),
    success: "Bedankt. We nemen persoonlijk contact met je op.",
    errors: {
      required: "Dit veld is verplicht.",
      email: "Vul een geldig e-mailadres in.",
      consent: draft("Ga akkoord met het privacybeleid om het bericht te versturen."),
      tooLong: draft("Dit veld is te lang."),
      rateLimited: draft("Te veel berichten in korte tijd. Probeer het later opnieuw."),
      failed: draft("Het bericht kon niet worden verstuurd. Probeer het later opnieuw of stuur een e-mail."),
    },
  },
  about: {
    title: "Over ons",
    promiseLabel: draft("Belofte"),
    promise: "Van oud naar waardevol",
    managementTitle: "Bestuur",
  },
  legal: {
    lastUpdated: "Laatst bijgewerkt",
    placeholderNote: "Placeholder: definitieve tekst volgt van legal.",
  },
  footer: {
    links: [
      { key: "privacy", label: "Privacybeleid" },
      { key: "cookies", label: "Cookiebeleid" },
      { key: "disclaimer", label: "Disclaimer" },
      { key: "colophon", label: "Colofon" },
    ],
    copyright: (year) => `© ${year}`,
    kvk: "KvK",
    vat: "BTW",
    linkedin: "LinkedIn",
    // Contactband: DESIGN §10.1 (7. Contact) letterlijk
    cta: { label: "Contact", title: "Neem contact op", body: "Voor samenwerking, pers of andere vragen: we reageren persoonlijk.", button: "Neem contact op" },
    mailUs: draft("Mail ons"),
    backToTop: draft("Naar boven"),
  },
  notFound: { title: "Deze pagina bestaat niet (meer)", home: draft("Terug naar de homepage") },
  placeholders: {
    description: "Placeholder: geverifieerde bedrijfsomschrijving (2–3 zinnen) volgt van Supreme.",
    story: "Placeholder: kort, geverifieerd bedrijfsverhaal volgt van Supreme.",
    media: "Placeholder: gelicentieerde fotografie volgt.",
    film: "Placeholder: herofilm en poster volgen van de filmmaker.",
    credits: "Placeholder: foto- en filmcredits volgen van Supreme.",
    // Fictional stand-ins for the header menu (owner's request 2026-10-01); replaced by company.json once verified.
    address: [draft("Voorbeeldstraat 12"), draft("1000 AA Amsterdam")],
    phone: draft("+31 20 000 00 00"),
    social: [draft("LinkedIn"), draft("Instagram"), draft("Facebook")],
  },
};
