import type { Copy } from "./copy.types";
import { draft } from "./draft";

export const en: Copy = {
  siteName: "Supreme Real Estate",
  meta: {
    homeTitle: "Supreme Real Estate · From old to valuable",
    titlePattern: (page) => `${page} · Supreme Real Estate`,
    description: "Supreme Real Estate is a real-estate company in Amsterdam, focused on existing homes and the long term.",
    pages: {
      about: { title: "About", description: draft("About Supreme Real Estate: what we stand for and our company details.") },
      contact: { title: "Contact", description: draft("Get in touch with Supreme Real Estate for partnerships, press or other questions.") },
      privacy: { title: "Privacy policy", description: draft("Privacy policy of Supreme Real Estate.") },
      cookies: { title: "Cookie policy", description: draft("Cookie policy of Supreme Real Estate.") },
      disclaimer: { title: "Disclaimer", description: draft("Disclaimer of Supreme Real Estate.") },
      colophon: { title: "Colophon", description: draft("Colophon of Supreme Real Estate: company details and credits.") },
    },
    notFoundTitle: "This page does not exist (anymore)",
  },
  a11y: {
    skip: draft("Skip to content"),
    languageSwitch: draft("Language"),
    nl: "Nederlands",
    en: "English",
    mainNav: draft("Main menu"),
    footerNav: draft("Legal"),
    legalNav: draft("Legal pages"),
    home: draft("Supreme Real Estate, to the homepage"),
  },
  nav: {
    about: "About",
    contact: "Contact",
    menu: draft("Navigate to"),
    closeMenu: "Close menu",
    contactUs: draft("Contact us"),
    // Section by section (owner's note 2026-10-01); grows with the homepage
    sections: [
      { id: "home", label: draft("Home") },
      { id: "about", label: "About" },
      { id: "approach", label: draft("How we work") },
    ],
  },
  brand: { wordmark: "SUPREME", descriptor: "REAL ESTATE", tagline: "From old to valuable" },
  hero: {
    // Hero concept 2026-09-30 (owner-supplied). Approved brand promise "From old to valuable." stays in the docs.
    headline: draft("Beyond\nSpaces for Living"),
    keyMessage: draft("Creating value through property and perspective."),
    pause: "Pause video",
    play: "Play video",
  },
  // Shelf statement: owner concept 2026-09-30 (draft until approved).
  shelf: {
    parts: [draft("We unlock the potential of existing"), { icon: "bulb" }, draft("properties, transforming"), { icon: "hammer" }, draft("them into thoughtfully designed homes and continuing to manage"), { icon: "clipboard" }, draft("their value over time"), { icon: "chart" }],
  },
  // Steps: owner concept 2026-10-01 (three steps verbatim from the owner's mock-up; headline lines draft).
  steps: {
    label: draft("Reimagining value"),
    lines: [draft("Unlocking potential."), draft("Transforming properties."), draft("Creating lasting value.")],
    items: [
      { index: "01", title: draft("Reimagine"), body: draft("Understanding the existing property and its potential.") },
      { index: "02", title: draft("Divide"), body: draft("Transforming larger spaces into independent homes.") },
      { index: "03", title: draft("Deliver"), body: draft("Completing each apartment as a turnkey living experience.") },
    ],
  },
  // Sky band: owner concept 2026-10-01 (drafts until approved). The seventh card completes the arc.
  sky: {
    label: draft("From"),
    title: draft("Potential to Turnkey"),
    lead: draft("We transform existing properties into thoughtfully designed, ready-to-live spaces."),
    cta: draft("See projects"),
    cards: [
      { title: draft("Potential"), body: draft("Identifying opportunities") },
      { title: draft("Acquire"), body: draft("Existing properties with potential") },
      { title: draft("Reimagined"), body: draft("A new vision for valuable spaces") },
      { title: draft("Transformed"), body: draft("Thoughtful development and high-quality design") },
      { title: draft("Refined"), body: draft("Modern living with timeless details") },
      { title: draft("Turnkey"), body: draft("Ready-to-live homes, completed to a high standard") },
      { title: draft("Lasting"), body: draft("Value that holds over time") },
    ],
  },
  statement: {
    label: draft("01 — Supreme"),
    text: "We see what a home can become, and give it a new future with care. Carefully chosen, renewed with craft, for the long term.",
    aside: draft("No quick transactions. We work with a horizon of decades, in the city we call home."),
  },
  principles: {
    label: draft("02 — Principles"),
    title: "What we stand for",
    sub: draft("Three principles behind every decision."),
    items: [
      { index: "01", title: "Careful", body: "We choose with attention and work with people who deliver craftsmanship." },
      { index: "02", title: "Lasting", body: "What we renew should last for generations." },
      { index: "03", title: "Long term", body: "We think in decades, not in transactions." },
    ],
  },
  carousel: {
    label: draft("03 — Details"),
    title: "Material, light and space",
    sub: draft("What lasts begins with what you touch and see."),
    items: [
      { title: draft("Material"), body: draft("Lime, stone, oak and brass. Materials that grow more beautiful with time.") },
      { title: draft("Light"), body: draft("Daylight as a building material: high, soft and present all day.") },
      { title: draft("Space"), body: draft("Space that gives calm, with measure and proportion that feel right.") },
    ],
  },
  map: {
    label: draft("04 — Amsterdam"),
    title: draft("At home in Amsterdam"),
    sub: draft("We work in the city we call home, with respect for what already stands."),
    cta: "About Supreme",
    dot: "Amsterdam",
  },
  closing: {
    title: draft("Made to last"),
    body: "For partnerships, press or other questions: we reply personally.",
    cta: "Get in touch",
    marquee: "From old to valuable",
  },
  details: {
    label: draft("03 — Details"),
    title: "Material, light and space",
    counter: (i, n) => `${i} / ${n}`,
    scrollerLabel: draft("Images of material, light and space"),
  },
  companySection: { label: draft("04 — Company"), title: "Company details" },
  companyKeys: {
    legalName: draft("Legal name"),
    tradeName: draft("Trade name"),
    kvk: draft("Chamber of Commerce (KvK) number"),
    visitingAddress: draft("Visiting address"),
    postalAddress: draft("Postal address"),
    vat: draft("VAT number"),
    email: draft("Email"),
    emailLegal: draft("Email (legal)"),
    phone: draft("Phone"),
    availability: draft("Availability"),
    management: draft("Management"),
    linkedin: "LinkedIn",
  },
  companyLegalLine: "For legal or compliance questions",
  contactSection: {
    label: draft("05 — Contact"),
    title: "Get in touch",
    body: "For partnerships, press or other questions: we reply personally.",
    cta: "Get in touch",
  },
  contactPage: {
    title: "Contact",
    lead: "For partnerships, press or other questions: we reply personally.",
    methodsTitle: draft("Reach us"),
    formTitle: draft("Send a message"),
  },
  form: {
    name: draft("Name"),
    organisation: draft("Organisation"),
    email: draft("Email"),
    phone: draft("Phone"),
    subject: draft("Subject"),
    message: draft("Message"),
    optional: draft("optional"),
    subjects: [
      { value: "samenwerking", label: draft("Partnership") },
      { value: "pers", label: draft("Press") },
      { value: "juridisch", label: draft("Legal / compliance") },
      { value: "overig", label: draft("Other") },
    ],
    subjectPlaceholder: draft("Choose a subject"),
    consent: draft("I agree to the processing of my data according to the"),
    consentLink: "Privacy policy",
    submit: "Send message",
    sending: draft("Sending…"),
    success: "Thank you. We will contact you personally.",
    errors: {
      required: "This field is required.",
      email: "Enter a valid email address.",
      consent: draft("Agree to the privacy policy to send the message."),
      tooLong: draft("This field is too long."),
      rateLimited: draft("Too many messages in a short time. Please try again later."),
      failed: draft("The message could not be sent. Please try again later or send an email."),
    },
  },
  about: {
    title: "About",
    promiseLabel: draft("Promise"),
    promise: "From old to valuable",
    managementTitle: draft("Management"),
  },
  legal: {
    lastUpdated: draft("Last updated"),
    placeholderNote: "Placeholder: final text to follow from legal.",
  },
  footer: {
    links: [
      { key: "privacy", label: "Privacy policy" },
      { key: "cookies", label: "Cookie policy" },
      { key: "disclaimer", label: "Disclaimer" },
      { key: "colophon", label: "Colophon" },
    ],
    copyright: (year) => `© ${year}`,
    kvk: "KvK",
    vat: draft("VAT"),
    linkedin: "LinkedIn",
  },
  notFound: { title: "This page does not exist (anymore)", home: draft("Back to the homepage") },
  placeholders: {
    description: "Placeholder: verified company description (2–3 sentences) to follow from Supreme.",
    story: "Placeholder: short, verified company story to follow from Supreme.",
    media: "Placeholder: licensed photography to follow.",
    film: "Placeholder: hero film and poster to follow from the film maker.",
    credits: "Placeholder: photo and film credits to follow from Supreme.",
    // Fictional stand-ins for the header menu (owner's request 2026-10-01); replaced by company.json once verified.
    address: [draft("Example street 12"), draft("1000 AA Amsterdam")],
    phone: draft("+31 20 000 00 00"),
  },
};
