import heroBoat from "./hero-film-03-boat.json";
/**
 * Media slots. null = asset not delivered yet; the UI renders a neutral placeholder frame.
 * File names must be neutral (DESIGN §2); scripts/check-filenames.ts enforces a pattern list.
 * Alt text lives here per language and describes what is visible, never an address.
 */
export type Ratio = "16/9" | "4/5" | "1/1" | "21/9";

export type ImageAsset = {
  /** Base name without extension, under /public/media (pipeline output). */
  src: string;
  width: number;
  height: number;
  alt: { nl: string; en: string };
  /** Transparent source: the pipeline wrote a PNG fallback instead of JPEG. */
  alpha?: boolean;
};

export type VideoAsset = {
  webm: string | null;
  mp4: string | null;
  /** ≤980px source (720p), optional. */
  mp4Mobile: string | null;
  /** The same films in HEVC (scripts/film-export.swift, FILM_CODEC=hevc), played where the browser decodes it (lib/film). */
  hevc?: string;
  hevcMobile?: string;
  poster: ImageAsset | null;
  /** Play once and hold the last frame (a story film), or loop. */
  loop: boolean;
  /** Playback speed (1 = as encoded). */
  rate?: number;
  /** A subject crossing the film that copy can sit behind (components/sections/HeroBoat). */
  subject?: FilmSubject;
};

/**
 * Outline of a rigid subject in film pixels (traced on one frame) and its offset [dx, dy] on every frame, or null
 * where it is out of view. Generated by scripts/film-matte.swift.
 */
export type FilmSubject = { fps: number; poly: [number, number][]; frames: ([number, number] | null)[] };

/**
 * Looping clip with transparency: one H.264 file carrying the colour on top and the matte (alpha as grey)
 * below a short black gap (scripts/film-stack.swift); the page composites it on a canvas. Still = keyed first frame.
 */
export type AlphaVideoAsset = {
  mp4: string;
  /** ≤980px version, optional. */
  mp4Mobile: string | null;
  /** HEVC encodes of both, played where the browser decodes it (lib/film). */
  hevc?: string;
  hevcMobile?: string;
  /** Size of one frame (the file is twice as tall plus the gap). */
  width: number;
  height: number;
  /** Black rows between the colour and the matte. */
  gap: number;
  poster: ImageAsset;
};

export type MediaSlot = { id: string; ratio: Ratio; image: ImageAsset | null };


/**
 * Hero still (concept 3, 2026-10-05): the first frame of the canal film, a row of gabled canal houses in
 * morning light. Atmosphere only: a generated scene, no house numbers, no street or neighbourhood (PRD §6.2).
 * hero-still-02 (white house, concept 2) and hero-still-01 (mock-up) stay for reference.
 * Note: generated render; DESIGN §12 asks for real photography before launch.
 */
export const heroStill: ImageAsset = {
  src: "hero-still-03",
  width: 1920,
  height: 1080,
  alt: { nl: "Grachtenpanden aan het water in het ochtendlicht", en: "Canal houses along the water in morning light" },
};


/**
 * Fourteen small interior details (the former homepage intro, retired 2026-10-05; still the parked Sky band's
 * thumbnails). Details, materials and light only, nothing traceable to an address (PRD §6.2).
 */
const intro = (src: string, width: number, height: number, nl: string, en: string): ImageAsset => ({ src, width, height, alt: { nl, en } });
export const introSequence: ImageAsset[] = [
  intro("intro-attic-01", 2160, 1440, "Zolder in vernieuwing", "An attic being renewed"),
  intro("intro-tap-01", 1333, 2000, "Kraan en ronde spiegel", "A tap and a round mirror"),
  intro("intro-doors-01", 2160, 1440, "Witte deuren in een gang", "White doors in a corridor"),
  intro("intro-tap-02", 1440, 2160, "Kraan boven een stenen blad", "A tap above a stone worktop"),
  intro("intro-basin-01", 1440, 2160, "Licht op een wastafel", "Light on a basin"),
  intro("intro-room-01", 4032, 3024, "Lege vernieuwde kamer", "An empty renewed room"),
  intro("intro-stone-01", 1440, 2160, "Natuursteen in een douche", "Natural stone in a shower"),
  intro("intro-stone-02", 2160, 1440, "Stenen wastafel en spiegel", "A stone basin and mirror"),
  intro("intro-wood-01", 2160, 1440, "Houten lamellen naast een wand", "Wooden slats beside a wall"),
  intro("intro-attic-02", 2160, 1440, "Nok van een zolder", "The ridge of an attic"),
  intro("intro-corridor-01", 3000, 2000, "Gang met daglicht", "A corridor in daylight"),
  intro("intro-entrance-01", 2153, 1440, "Entree met houten lamellen", "An entrance with wooden slats"),
  intro("intro-room-02", 2160, 1440, "Lichte kamer met houten vloer", "A light room with a wooden floor"),
  intro("intro-stair-01", 2160, 1440, "Trap in daglicht", "A stair in daylight"),
];

/**
 * Hero film (concept 3, supplied 2026-10-05): fixed camera on the canal houses, boats passing, loops. Trimmed to
 * 0.083–9.333 s (retimed to 24 fps from zero), where the second boat stands exactly where the first one starts,
 * so the loop has no seam; then raised to 60 fps with motion interpolation (scripts/film-interpolate.swift).
 * Re-encoded without metadata or audio by scripts/film-export.swift (the concept-2 films, hero-film-01/02, live on the
 * hero-concept-2 branch only). WebM pending (no ffmpeg on the build machine). Note: generated render; DESIGN §12 asks for real film.
 */
export const heroFilm: VideoAsset = {
  webm: null,
  mp4: "/media/hero-film-03.mp4",
  mp4Mobile: "/media/hero-film-03-720.mp4",
  hevc: "/media/hero-film-hevc-03.mp4",
  hevcMobile: "/media/hero-film-hevc-03-720.mp4",
  poster: heroStill,
  loop: true,
  rate: 0.65, // a canal boat's own pace (owner, 2026-10-07: slower, realistic); the night film keeps the same pace
  subject: heroBoat as FilmSubject, // the tour boat; the headline sits behind it
};


/**
 * Night film (supplied 2026-10-05): the same view after dark, windows lit, a boat passing. Trimmed to a seamless
 * loop (1.4167–9.9167 s, the last frame meeting the first with the boat at the very edge) and raised to 60 fps like
 * the day film. Carries the dusk: it comes up over the day film as the page scrolls, and once night has fallen it
 * stops looping and rests on its last frame (HeroNightFilm / HeroScroll).
 */
export const heroNightFilm: VideoAsset = {
  webm: null,
  mp4: "/media/hero-film-04.mp4",
  mp4Mobile: "/media/hero-film-04-720.mp4",
  hevc: "/media/hero-film-hevc-04.mp4",
  hevcMobile: "/media/hero-film-hevc-04-720.mp4",
  poster: heroStill,
  loop: true,
  rate: 0.65,
};

/**
 * Project interior (owner-supplied render, 2026-10-05): the room the first project window opens onto. Used as the
 * window preview and the fullscreen interior (components/windows). Neutral file name (PRD §6.2).
 */
export const interiorLiving: ImageAsset = {
  src: "interior-living-01",
  width: 1672,
  height: 941,
  alt: { nl: "Lichte woonkamer met open keuken in avondlicht", en: "A bright living room with an open kitchen in evening light" },
};

/**
 * Shelf section (concept 2026-09-30). The shelf is a transparent cut-out; each icon has its compartment as a
 * centre point and width in % of the shelf image. Icons supplied at 90 px are placeholders until the final
 * assets arrive (they will need ≥ 512 px).
 */
export type ShelfIconAsset = ImageAsset & { slot: { x: number; y: number; w: number } };
export const shelfImage: ImageAsset = { src: "shelf-01", width: 968, height: 695, alt: { nl: "Open kast met boeken en objecten", en: "An open shelf with books and objects" } };
export const shelfIcons: Record<"bulb" | "hammer" | "clipboard" | "chart", ShelfIconAsset> = {
  bulb: { src: "icon-bulb-01", width: 90, height: 90, alt: { nl: "Idee: lamp met een huis", en: "Idea: a bulb with a house" }, slot: { x: 10.2, y: 63.5, w: 11 } },
  hammer: { src: "icon-hammer-01", width: 90, height: 90, alt: { nl: "Vernieuwen: hamer en bouwstenen", en: "Renewing: a hammer and building blocks" }, slot: { x: 62, y: 79, w: 12 } },
  clipboard: { src: "icon-clipboard-01", width: 90, height: 90, alt: { nl: "Beheren: checklist met een huis", en: "Managing: a checklist with a house" }, slot: { x: 28, y: 81.5, w: 13.5 } },
  chart: { src: "icon-chart-01", width: 90, height: 90, alt: { nl: "Waarde: stijgende grafiek", en: "Value: a rising chart" }, slot: { x: 85.4, y: 82, w: 13.5 } },
};

/**
 * Steps section: one looping clip per step (supplied 2026-10-02, 4 s, a canal house on a flat ground).
 * The ground was keyed to transparency offline (scripts/film-frames.swift → scripts/key-clips.mjs: background model,
 * shadow kept as a multiply layer) and the keyed frames stacked into colour + matte video (scripts/film-stack.swift).
 * Kept at their own 24 fps: raised to 60 fps by motion interpolation, the robot's quick moves and the renewal sweep
 * came out ghosted (two robots, a smeared band), so the clips play their source frames only.
 */
const stepClip = (n: string, nl: string, en: string): AlphaVideoAsset => ({
  mp4: `/media/step-clip-${n}.mp4`,
  mp4Mobile: `/media/step-clip-${n}-720.mp4`,
  hevc: `/media/step-clip-hevc-${n}.mp4`,
  hevcMobile: `/media/step-clip-hevc-${n}-720.mp4`,
  width: 960,
  height: 719,
  gap: 8,
  poster: { src: `step-poster-${n}`, width: 960, height: 719, alpha: true, alt: { nl, en } },
});
export const stepsClips: AlphaVideoAsset[] = [
  stepClip("01", "Grachtenpand met een kleine inspectierobot", "A canal house with a small survey robot"),
  stepClip("02", "Grachtenpand in de steigers, gevel wordt vernieuwd", "A canal house in scaffolding, its front being renewed"),
  stepClip("03", "Vernieuwd grachtenpand met verlichte ramen", "A renewed canal house with lit windows"),
];
/**
 * Mascots (owner-supplied renders, 2026-10-02): the toolbox robot with a tool each, cut-outs on transparent.
 * They orbit the "see our work" line that introduces the projects. Decorative: no alt text in the page.
 */
const mascot = (src: string, nl: string, en: string): ImageAsset => ({ src, width: 1024, height: 1024, alpha: true, alt: { nl, en } });
export const mascots: ImageAsset[] = [
  mascot("mascot-drill-01", "Mascotte met een boormachine", "Mascot holding a drill"),
  mascot("mascot-plan-01", "Mascotte leest een plattegrond", "Mascot reading a floor plan"),
  mascot("mascot-roller-01", "Mascotte met een verfroller", "Mascot holding a paint roller"),
  mascot("mascot-laptop-01", "Mascotte achter een laptop", "Mascot behind a laptop"),
  mascot("mascot-tools-01", "Mascotte vol gereedschap", "Mascot full of tools"),
  mascot("mascot-bulb-01", "Mascotte met een idee", "Mascot with an idea"),
  mascot("mascot-wrench-01", "Mascotte met een moersleutel", "Mascot holding a wrench"),
];

/**
 * Orbit cards (owner-supplied renders, 2026-10-03): four square cards that circle the projects headline between the
 * mascots, each with its word on it (Architects, Builders, Partners, Designers). Cut from their black background
 * with a small corner radius; generated images, no real place. Decorative in the page.
 */
const card = (src: string, width: number, height: number, nl: string, en: string): ImageAsset => ({ src, width, height, alpha: true, alt: { nl, en } });
export const orbitCards: ImageAsset[] = [
  card("card-architects-01", 909, 964, "Kaart: maquette en tekeningen", "Card: a model and drawings"),
  card("card-builders-01", 940, 1004, "Kaart: twee bouwers op een werk", "Card: two builders on site"),
  card("card-partners-01", 943, 1005, "Kaart: een handdruk boven een maquette", "Card: a handshake over a model"),
  card("card-designers-01", 941, 1004, "Kaart: ontwerpers bij een scherm", "Card: designers at a screen"),
];




/**
 * Project pages (2026-10-06): the photographs and before/after pairs of the four featured projects, under neutral
 * names (case-<a..d>-NN, before-<b|c>-NN; a = Durgerdammergouw, b = Prinsen Bolwerk, c = Schoterweg,
 * d = Bezaanjachtplein). Interiors and works in progress only: no facades, no street, no faces (PRD §6.2).
 * Each project's own photographs from the owner's old site (2026-10-07: matched to the projects' own pages there,
 * replacing stand-ins from other projects). Interiors only (no facades, no street, no faces, no shop signage); for
 * Durgerdammergouw, which has no interiors yet, the plot from the air. Alt text says what is visible.
 */
const room = (src: string, width: number, height: number, nl: string, en: string): ImageAsset => ({ src, width, height, alt: { nl, en } });
export const caseImages = {
  // Durgerdammergouw: a former livestock farm in the polder; no interiors exist yet, so the plot from the air
  a: [room("case-a-01", 2160, 1440, "De polder van bovenaf, met sloten en weilanden langs het water", "The polder from the air, with ditches and meadows along the water")],
  b: [
    room("case-b-01", 2157, 1440, "Hoge woonkamer met kroonluchter, houten vloer en twee hoge ramen", "A tall living room with a chandelier, wooden floor and two tall windows"),
    room("case-b-02", 2156, 1440, "Woon- en eetverdieping met balkenplafond en dakraam", "A living and dining floor with a beamed ceiling and a skylight"),
  ],
  c: [
    room("case-c-01", 2160, 1440, "Witte keuken met kookeiland en hoge ramen", "A white kitchen with an island and tall windows"),
    room("case-c-02", 2157, 1440, "Woonkamer met glas-in-loodramen en open keuken", "A living room with stained-glass windows and an open kitchen"),
    room("case-c-03", 2157, 1440, "Woonkamer met blauwe hoekbank en eiken schuifdeur", "A living room with a blue corner sofa and an oak sliding door"),
    room("case-c-04", 2155, 1440, "Eethoek en keuken onder een dakraam", "A dining area and kitchen under a skylight"),
    room("case-c-05", 2158, 1440, "Badkamer met ronde spiegel en ligbad", "A bathroom with a round mirror and a bath"),
  ],
  d: [
    room("case-d-01", 2400, 1600, "Woonkamer met eettafel en keuken", "A living room with a dining table and kitchen"),
    room("case-d-02", 2400, 1600, "Open keuken met eiland en woonkamer", "An open kitchen with an island and living room"),
    room("case-d-03", 2400, 1600, "Keuken met eiland en barkrukken", "A kitchen with an island and bar stools"),
    room("case-d-04", 2400, 1600, "Witte keuken met eettafel", "A white kitchen with a dining table"),
    room("case-d-05", 2400, 1600, "Woonkamer met grijze bank", "A living room with a grey sofa"),
    room("case-d-06", 2400, 1600, "Slaapkamer met kastwand", "A bedroom with built-in wardrobes"),
    room("case-d-07", 1333, 2000, "Badkamer met zwarte wastafel", "A bathroom with a black basin"),
    room("case-d-08", 2400, 1600, "Slaapkamer met oranje sprei", "A bedroom with an orange bedspread"),
    room("case-d-09", 2400, 1600, "Lichte slaapkamer met groot raam", "A bright bedroom with a large window"),
  ],
};
/** The same rooms during the works (3:2 crops, to sit under their finished photos in the before/after frame). */
export const beforeImages = {
  c: [room("before-c-01", 2400, 1600, "Dezelfde keuken tijdens de verbouwing", "The same kitchen during the renovation")],
}

/**
 * The homepage project cards (2026-10-07): up to three photographs from each project's own set (caseImages above,
 * plus Durgerdammergouw's render), so a card shows the project it names.
 */
export const workCases: { id: string; photos: ImageAsset[] }[] = [
  { id: "a", photos: [interiorLiving, caseImages.a[0]] },
  { id: "b", photos: [caseImages.b[0], caseImages.b[1]] },
  { id: "c", photos: [caseImages.c[0], caseImages.c[1], caseImages.c[4]] },
  { id: "d", photos: [caseImages.d[2], caseImages.d[6], caseImages.d[8]] },
];

/** Line drawings cut from the owner's concept image (2026-10-01): white lines on transparent, for dark bands. */
export const stepsSketches: { left: MediaSlot; right: MediaSlot } = {
  left: { id: "sketch-01", ratio: "1/1", image: { src: "sketch-house-01", width: 470, height: 470, alpha: true, alt: { nl: "Lijntekening van een grachtenpand", en: "Line drawing of a canal house" } } },
  right: { id: "sketch-02", ratio: "1/1", image: { src: "sketch-block-01", width: 500, height: 500, alpha: true, alt: { nl: "Lijntekening van een modern woongebouw", en: "Line drawing of a modern apartment building" } } },
};

/** Sky band background (owner concept 2026-10-01): canal-house gables against a morning sky. Generated render. */
export const skyImage: ImageAsset = { src: "sky-gables-01", width: 1672, height: 941, alt: { nl: "Gevels tegen een ochtendlucht", en: "Gables against a morning sky" } };

/** Footer: the same two line drawings in ink, for the Stone footer band. */
export const footerSketches: { left: ImageAsset; right: ImageAsset } = {
  left: { src: "sketch-house-ink-01", width: 470, height: 470, alpha: true, alt: { nl: "Lijntekening van een grachtenpand", en: "Line drawing of a canal house" } },
  right: { src: "sketch-block-ink-01", width: 500, height: 500, alpha: true, alt: { nl: "Lijntekening van een modern woongebouw", en: "Line drawing of a modern apartment building" } },
};

/** Optional cut-out subject layer over the hero (transparent PNG/WebP, e.g. a renewed volume or window). */
export const heroSubject: MediaSlot = { id: "hero-subject", ratio: "4/5", image: null };

/** Two capsule images under the statement. */
export const statementCapsules: MediaSlot[] = [
  { id: "capsule-01", ratio: "16/9", image: null },
  { id: "capsule-02", ratio: "16/9", image: null },
];

/** Pinned principles section: a tall vertical image (stair, wall, window) and one small thumbnail. */
export const principlesTall: MediaSlot = { id: "principles-tall", ratio: "4/5", image: null };
export const principlesThumb: MediaSlot = { id: "principles-thumb", ratio: "1/1", image: null };

/** Carousel photo cards, one per pair (Materiaal · Licht · Ruimte). */
export const carouselImages: MediaSlot[] = [
  { id: "pair-01", ratio: "4/5", image: null },
  { id: "pair-02", ratio: "4/5", image: null },
  { id: "pair-03", ratio: "4/5", image: null },
];

/** Closing: the capsule that grows into the wide footer image, and the small capsule at the end of the wordmark. */
export const closingCapsule: MediaSlot = { id: "closing-01", ratio: "21/9", image: null };
export const wordmarkCapsule: MediaSlot = { id: "closing-02", ratio: "16/9", image: null };

export const principlesMedia: MediaSlot = { id: "principles", ratio: "21/9", image: null };

export const detailSequence: MediaSlot[] = [
  { id: "detail-01", ratio: "4/5", image: null },
  { id: "detail-02", ratio: "16/9", image: null },
  { id: "detail-03", ratio: "1/1", image: null },
  { id: "detail-04", ratio: "16/9", image: null },
  { id: "detail-05", ratio: "4/5", image: null },
];

export const impressions: { wide: MediaSlot; left: MediaSlot; right: MediaSlot } = {
  wide: { id: "impression-01", ratio: "21/9", image: null },
  left: { id: "impression-02", ratio: "4/5", image: null },
  right: { id: "impression-03", ratio: "16/9", image: null },
};

export const aboutHero: MediaSlot = { id: "about-01", ratio: "21/9", image: null };
