import heroBoat from "./hero-film-03-boat.json";
/**
 * Media slots. null = asset not delivered yet; the UI renders a neutral placeholder frame.
 * File names must be neutral (DESIGN §2); scripts/check-filenames.ts enforces a pattern list.
 * Alt text lives here per language and describes what is visible, never an address.
 */
export type Ratio = "16/9" | "4/5" | "1/1" | "21/9";

export type ImageAsset = {
  /** Base name without extension, under /public/media (pipeline output). */
  src: string;
  width: number;
  height: number;
  alt: { nl: string; en: string };
  /** Transparent source: the pipeline wrote a PNG fallback instead of JPEG. */
  alpha?: boolean;
};

export type VideoAsset = {
  webm: string | null;
  mp4: string | null;
  /** ≤980px source (720p), optional. */
  mp4Mobile: string | null;
  poster: ImageAsset | null;
  /** Play once and hold the last frame (a story film), or loop. */
  loop: boolean;
  /** Playback speed (1 = as encoded). */
  rate?: number;
  /** A subject crossing the film that copy can sit behind (components/sections/HeroBoat). */
  subject?: FilmSubject;
};

/**
 * Outline of a rigid subject in film pixels (traced on one frame) and its offset [dx, dy] on every frame, or null
 * where it is out of view. Generated by scripts/film-matte.swift.
 */
export type FilmSubject = { fps: number; poly: [number, number][]; frames: ([number, number] | null)[] };

/**
 * Looping clip with transparency: one H.264 file carrying the colour on top and the matte (alpha as grey)
 * below a short black gap (scripts/film-stack.swift); the page composites it on a canvas. Still = keyed first frame.
 */
export type AlphaVideoAsset = {
  mp4: string;
  /** ≤980px version, optional. */
  mp4Mobile: string | null;
  /** Size of one frame (the file is twice as tall plus the gap). */
  width: number;
  height: number;
  /** Black rows between the colour and the matte. */
  gap: number;
  poster: ImageAsset;
};

export type MediaSlot = { id: string; ratio: Ratio; image: ImageAsset | null };


/**
 * Hero still (concept 3, 2026-10-05): the first frame of the canal film, a row of gabled canal houses in
 * morning light. Atmosphere only: a generated scene, no house numbers, no street or neighbourhood (PRD §6.2).
 * hero-still-02 (white house, concept 2) and hero-still-01 (mock-up) stay for reference.
 * Note: generated render; DESIGN §12 asks for real photography before launch.
 */
export const heroStill: ImageAsset = {
  src: "hero-still-03",
  width: 1920,
  height: 1080,
  alt: { nl: "Grachtenpanden aan het water in het ochtendlicht", en: "Canal houses along the water in morning light" },
};


/**
 * Fourteen small interior details (the former homepage intro, retired 2026-10-05; still the parked Sky band's
 * thumbnails). Details, materials and light only, nothing traceable to an address (PRD §6.2).
 */
const intro = (src: string, width: number, height: number, nl: string, en: string): ImageAsset => ({ src, width, height, alt: { nl, en } });
export const introSequence: ImageAsset[] = [
  intro("intro-attic-01", 2160, 1440, "Zolder in vernieuwing", "An attic being renewed"),
  intro("intro-tap-01", 1333, 2000, "Kraan en ronde spiegel", "A tap and a round mirror"),
  intro("intro-doors-01", 2160, 1440, "Witte deuren in een gang", "White doors in a corridor"),
  intro("intro-tap-02", 1440, 2160, "Kraan boven een stenen blad", "A tap above a stone worktop"),
  intro("intro-basin-01", 1440, 2160, "Licht op een wastafel", "Light on a basin"),
  intro("intro-room-01", 4032, 3024, "Lege vernieuwde kamer", "An empty renewed room"),
  intro("intro-stone-01", 1440, 2160, "Natuursteen in een douche", "Natural stone in a shower"),
  intro("intro-stone-02", 2160, 1440, "Stenen wastafel en spiegel", "A stone basin and mirror"),
  intro("intro-wood-01", 2160, 1440, "Houten lamellen naast een wand", "Wooden slats beside a wall"),
  intro("intro-attic-02", 2160, 1440, "Nok van een zolder", "The ridge of an attic"),
  intro("intro-corridor-01", 3000, 2000, "Gang met daglicht", "A corridor in daylight"),
  intro("intro-entrance-01", 2153, 1440, "Entree met houten lamellen", "An entrance with wooden slats"),
  intro("intro-room-02", 2160, 1440, "Lichte kamer met houten vloer", "A light room with a wooden floor"),
  intro("intro-stair-01", 2160, 1440, "Trap in daglicht", "A stair in daylight"),
];

/**
 * Hero film (concept 3, supplied 2026-10-05): fixed camera on the canal houses, boats passing, loops. Trimmed to
 * 0.083–9.333 s (retimed to 24 fps from zero), where the second boat stands exactly where the first one starts,
 * so the loop has no seam; then raised to 60 fps with motion interpolation (scripts/film-interpolate.swift).
 * Re-encoded without metadata or audio by scripts/film-export.swift (hero-film-02, the house renewal, also at 60 fps, stays
 * for concept 2). WebM pending (no ffmpeg on the build machine). Note: generated render; DESIGN §12 asks for real film.
 */
export const heroFilm: VideoAsset = {
  webm: null,
  mp4: "/media/hero-film-03.mp4",
  mp4Mobile: "/media/hero-film-03-720.mp4",
  poster: heroStill,
  loop: true,
  subject: heroBoat as FilmSubject, // the tour boat; the headline sits behind it
};

/**
 * Night still (supplied 2026-10-05): the same view after dark, windows lit, registered to the day film's first
 * frame (scale and shift found on edge maps, scratch script) so the crossfade never doubles the facades. Comes up
 * over the night film once dusk is done (HeroNight / HeroScroll); a still, so the view holds steady at night.
 */
export const heroNight: ImageAsset = {
  src: "hero-night-01",
  width: 1920,
  height: 1080,
  alt: { nl: "De grachtenpanden bij avond, de ramen verlicht", en: "The canal houses at night, their windows lit" },
};

/**
 * Night film (supplied 2026-10-05): the same view after dark, windows lit, a boat passing. Trimmed to a seamless
 * loop (1.4167–9.9167 s) and raised to 60 fps like the day film. Carries the dusk: it comes up over the day film as
 * the page scrolls, then hands over to the night still (HeroNight / HeroScroll).
 */
export const heroNightFilm: VideoAsset = {
  webm: null,
  mp4: "/media/hero-film-04.mp4",
  mp4Mobile: "/media/hero-film-04-720.mp4",
  poster: heroNight,
  loop: true,
};

/**
 * Project interior (owner-supplied render, 2026-10-05): the room the first project window opens onto. Used as the
 * window preview and the fullscreen interior (components/windows). Neutral file name (PRD §6.2).
 */
export const interiorLiving: ImageAsset = {
  src: "interior-living-01",
  width: 1672,
  height: 941,
  alt: { nl: "Lichte woonkamer met open keuken in avondlicht", en: "A bright living room with an open kitchen in evening light" },
};

/**
 * Shelf section (concept 2026-09-30). The shelf is a transparent cut-out; each icon has its compartment as a
 * centre point and width in % of the shelf image. Icons supplied at 90 px are placeholders until the final
 * assets arrive (they will need ≥ 512 px).
 */
export type ShelfIconAsset = ImageAsset & { slot: { x: number; y: number; w: number } };
export const shelfImage: ImageAsset = { src: "shelf-01", width: 968, height: 695, alt: { nl: "Open kast met boeken en objecten", en: "An open shelf with books and objects" } };
export const shelfIcons: Record<"bulb" | "hammer" | "clipboard" | "chart", ShelfIconAsset> = {
  bulb: { src: "icon-bulb-01", width: 90, height: 90, alt: { nl: "Idee: lamp met een huis", en: "Idea: a bulb with a house" }, slot: { x: 10.2, y: 63.5, w: 11 } },
  hammer: { src: "icon-hammer-01", width: 90, height: 90, alt: { nl: "Vernieuwen: hamer en bouwstenen", en: "Renewing: a hammer and building blocks" }, slot: { x: 62, y: 79, w: 12 } },
  clipboard: { src: "icon-clipboard-01", width: 90, height: 90, alt: { nl: "Beheren: checklist met een huis", en: "Managing: a checklist with a house" }, slot: { x: 28, y: 81.5, w: 13.5 } },
  chart: { src: "icon-chart-01", width: 90, height: 90, alt: { nl: "Waarde: stijgende grafiek", en: "Value: a rising chart" }, slot: { x: 85.4, y: 82, w: 13.5 } },
};

/**
 * Steps section: one looping clip per step (supplied 2026-10-02, 4 s, a canal house on a flat ground).
 * The ground was keyed to transparency offline (scripts/film-frames.swift → scripts/key-clips.mjs: background model,
 * shadow kept as a multiply layer), the keyed frames stacked into colour + matte video (scripts/film-stack.swift),
 * then raised from 24 to 60 fps with motion interpolation (scripts/film-interpolate.swift), matte and colour together.
 */
const stepClip = (n: string, nl: string, en: string): AlphaVideoAsset => ({
  mp4: `/media/step-clip-${n}.mp4`,
  mp4Mobile: `/media/step-clip-${n}-720.mp4`,
  width: 960,
  height: 719,
  gap: 8,
  poster: { src: `step-poster-${n}`, width: 960, height: 719, alpha: true, alt: { nl, en } },
});
export const stepsClips: AlphaVideoAsset[] = [
  stepClip("01", "Grachtenpand met een kleine inspectierobot", "A canal house with a small survey robot"),
  stepClip("02", "Grachtenpand in de steigers, gevel wordt vernieuwd", "A canal house in scaffolding, its front being renewed"),
  stepClip("03", "Vernieuwd grachtenpand met verlichte ramen", "A renewed canal house with lit windows"),
];
/**
 * Mascots (owner-supplied renders, 2026-10-02): the toolbox robot with a tool each, cut-outs on transparent.
 * They orbit the "see our work" line that introduces the projects. Decorative: no alt text in the page.
 */
const mascot = (src: string, nl: string, en: string): ImageAsset => ({ src, width: 1024, height: 1024, alpha: true, alt: { nl, en } });
export const mascots: ImageAsset[] = [
  mascot("mascot-drill-01", "Mascotte met een boormachine", "Mascot holding a drill"),
  mascot("mascot-plan-01", "Mascotte leest een plattegrond", "Mascot reading a floor plan"),
  mascot("mascot-roller-01", "Mascotte met een verfroller", "Mascot holding a paint roller"),
  mascot("mascot-laptop-01", "Mascotte achter een laptop", "Mascot behind a laptop"),
  mascot("mascot-tools-01", "Mascotte vol gereedschap", "Mascot full of tools"),
  mascot("mascot-bulb-01", "Mascotte met een idee", "Mascot with an idea"),
  mascot("mascot-wrench-01", "Mascotte met een moersleutel", "Mascot holding a wrench"),
];

/**
 * Orbit cards (owner-supplied renders, 2026-10-03): four square cards that circle the projects headline between the
 * mascots, each with its word on it (Architects, Builders, Partners, Designers). Cut from their black background
 * with a small corner radius; generated images, no real place. Decorative in the page.
 */
const card = (src: string, width: number, height: number, nl: string, en: string): ImageAsset => ({ src, width, height, alpha: true, alt: { nl, en } });
export const orbitCards: ImageAsset[] = [
  card("card-architects-01", 909, 964, "Kaart: maquette en tekeningen", "Card: a model and drawings"),
  card("card-builders-01", 940, 1004, "Kaart: twee bouwers op een werk", "Card: two builders on site"),
  card("card-partners-01", 943, 1005, "Kaart: een handdruk boven een maquette", "Card: a handshake over a model"),
  card("card-designers-01", 941, 1004, "Kaart: ontwerpers bij een scherm", "Card: designers at a screen"),
];

/**
 * Projects (concept 2026-10-02): four anonymised cases, three interiors each from the owner's archive under neutral
 * names (work-a..d). Interiors only: no facades, names, addresses or figures (PRD §6.2). Alt text says what is visible.
 */
const work = (src: string, width: number, height: number, nl: string, en: string): ImageAsset => ({ src, width, height, alt: { nl, en } });
export const workCases: { id: string; photos: ImageAsset[] }[] = [
  {
    id: "a",
    photos: [
      work("work-a-01", 3000, 2000, "Lichte woonkeuken met kookeiland", "A bright kitchen with an island"),
      work("work-a-02", 3000, 2000, "Slaapkamer met dakraam", "A bedroom under a skylight"),
      work("work-a-03", 1333, 2000, "Badkamer met zwarte wastafels", "A bathroom with black basins"),
    ],
  },
  {
    id: "b",
    photos: [
      work("work-b-01", 3000, 2000, "Donkere keuken met houten bar", "A dark kitchen with a wooden bar"),
      work("work-b-02", 1333, 2000, "Messing kraan bij een ronde spiegel", "A brass tap by a round mirror"),
      work("work-b-03", 3000, 2000, "Woonkamer met brede ramen", "A living room with wide windows"),
    ],
  },
  {
    id: "c",
    photos: [
      work("work-c-01", 2160, 1440, "Keuken met marmeren werkblad", "A kitchen with a marble worktop"),
      work("work-c-02", 2160, 1440, "Badkamer in natuursteen", "A bathroom in natural stone"),
      work("work-c-03", 2160, 1440, "Slaapkamer onder het dak", "A bedroom under the roof"),
    ],
  },
  {
    id: "d",
    photos: [
      work("work-d-01", 2160, 1440, "Woonkamer met open keuken", "A living room with an open kitchen"),
      work("work-d-02", 2158, 1440, "Badkamer met ronde spiegel", "A bathroom with a round mirror"),
      work("work-d-03", 2158, 1440, "Slaapkamer met uitzicht", "A bedroom with a view"),
    ],
  },
];

/** Line drawings cut from the owner's concept image (2026-10-01): white lines on transparent, for dark bands. */
export const stepsSketches: { left: MediaSlot; right: MediaSlot } = {
  left: { id: "sketch-01", ratio: "1/1", image: { src: "sketch-house-01", width: 470, height: 470, alpha: true, alt: { nl: "Lijntekening van een grachtenpand", en: "Line drawing of a canal house" } } },
  right: { id: "sketch-02", ratio: "1/1", image: { src: "sketch-block-01", width: 500, height: 500, alpha: true, alt: { nl: "Lijntekening van een modern woongebouw", en: "Line drawing of a modern apartment building" } } },
};

/** Sky band background (owner concept 2026-10-01): canal-house gables against a morning sky. Generated render. */
export const skyImage: ImageAsset = { src: "sky-gables-01", width: 1672, height: 941, alt: { nl: "Gevels tegen een ochtendlucht", en: "Gables against a morning sky" } };

/** Footer: the same two line drawings in ink, for the Stone footer band. */
export const footerSketches: { left: ImageAsset; right: ImageAsset } = {
  left: { src: "sketch-house-ink-01", width: 470, height: 470, alpha: true, alt: { nl: "Lijntekening van een grachtenpand", en: "Line drawing of a canal house" } },
  right: { src: "sketch-block-ink-01", width: 500, height: 500, alpha: true, alt: { nl: "Lijntekening van een modern woongebouw", en: "Line drawing of a modern apartment building" } },
};

/** Optional cut-out subject layer over the hero (transparent PNG/WebP, e.g. a renewed volume or window). */
export const heroSubject: MediaSlot = { id: "hero-subject", ratio: "4/5", image: null };

/** Two capsule images under the statement. */
export const statementCapsules: MediaSlot[] = [
  { id: "capsule-01", ratio: "16/9", image: null },
  { id: "capsule-02", ratio: "16/9", image: null },
];

/** Pinned principles section: a tall vertical image (stair, wall, window) and one small thumbnail. */
export const principlesTall: MediaSlot = { id: "principles-tall", ratio: "4/5", image: null };
export const principlesThumb: MediaSlot = { id: "principles-thumb", ratio: "1/1", image: null };

/** Carousel photo cards, one per pair (Materiaal · Licht · Ruimte). */
export const carouselImages: MediaSlot[] = [
  { id: "pair-01", ratio: "4/5", image: null },
  { id: "pair-02", ratio: "4/5", image: null },
  { id: "pair-03", ratio: "4/5", image: null },
];

/** Closing: the capsule that grows into the wide footer image, and the small capsule at the end of the wordmark. */
export const closingCapsule: MediaSlot = { id: "closing-01", ratio: "21/9", image: null };
export const wordmarkCapsule: MediaSlot = { id: "closing-02", ratio: "16/9", image: null };

export const principlesMedia: MediaSlot = { id: "principles", ratio: "21/9", image: null };

export const detailSequence: MediaSlot[] = [
  { id: "detail-01", ratio: "4/5", image: null },
  { id: "detail-02", ratio: "16/9", image: null },
  { id: "detail-03", ratio: "1/1", image: null },
  { id: "detail-04", ratio: "16/9", image: null },
  { id: "detail-05", ratio: "4/5", image: null },
];

export const impressions: { wide: MediaSlot; left: MediaSlot; right: MediaSlot } = {
  wide: { id: "impression-01", ratio: "21/9", image: null },
  left: { id: "impression-02", ratio: "4/5", image: null },
  right: { id: "impression-03", ratio: "16/9", image: null },
};

export const aboutHero: MediaSlot = { id: "about-01", ratio: "21/9", image: null };
